// Auto-generated by feishu_sync.py
// Last updated: 2026-08-17 18:40
window.DASHBOARD_DATA = {
  "tasks": {
    "date": "8月17日",
    "items": [
      {
        "text": "拆解1位博主，把拆解笔记的图片形式定下来",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "整理博主拆解的爆款笔记，总结爆款标题写法",
        "done": false,
        "cancelled": false,
        "priority": "mid"
      },
      {
        "text": "升级一下流产后身心恢复指南，定价为39.9元",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "写4篇小红书笔记",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "晚上用晗哥另外一个微信号完成微信补卡",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "运动1小时",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_text": "1.拆解1位博主，把拆解笔记的图片形式定下来\n2.整理博主拆解的爆款笔记，总结爆款标题写法\n3.升级一下流产后身心恢复指南，定价为39.9元\n4.写4篇小红书笔记\n5.晚上用晗哥另外一个微信号完成微信补卡\n6.运动1小时",
    "tasks": [
      {
        "text": "拆解1位博主，把拆解笔记的图片形式定下来",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "整理博主拆解的爆款笔记，总结爆款标题写法",
        "done": false,
        "cancelled": false,
        "priority": "mid"
      },
      {
        "text": "升级一下流产后身心恢复指南，定价为39.9元",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "写4篇小红书笔记",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "晚上用晗哥另外一个微信号完成微信补卡",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "运动1小时",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_tasks_text": "1.拆解1位博主，把拆解笔记的图片形式定下来\n2.整理博主拆解的爆款笔记，总结爆款标题写法\n3.升级一下流产后身心恢复指南，定价为39.9元\n4.写4篇小红书笔记\n5.晚上用晗哥另外一个微信号完成微信补卡\n6.运动1小时"
  },
  "memos": {
    "items": [
      {
        "date": "8月17日",
        "text": "拆解博主不是目的是工具，最终是要做好物博主",
        "id": "memo_55_0"
      },
      {
        "date": "8月15日",
        "text": "试管容易违规，尽量不讲",
        "id": "memo_53_0"
      },
      {
        "date": "8月5日",
        "text": "workbuddy的一人公司专家团用一下",
        "id": "memo_44_2"
      },
      {
        "date": "8月5日",
        "text": "小红书虚拟产品定位skill用一下",
        "id": "memo_44_1"
      },
      {
        "date": "8月5日",
        "text": "开发【嘎嘎有用】生活小程序",
        "id": "memo_44_0"
      },
      {
        "date": "7月31日",
        "text": "买个摄像头回家（放客厅看爸妈小耳朵）",
        "id": "memo_39_0"
      },
      {
        "date": "7月29日",
        "text": "流产后身心恢复指南，卖的更好，是不是可以继续开发类似的产品",
        "id": "memo_37_1"
      },
      {
        "date": "7月29日",
        "text": "孕期记录工作台：用 Workbuddy 搭孕期记录工具，先分享，如果很多人不会用可以打包成 skill 出售",
        "id": "memo_37_0"
      },
      {
        "date": "7月28日",
        "text": "学习红十字会急救培训课程",
        "id": "memo_36_6"
      },
      {
        "date": "7月28日",
        "text": "看3个AI分享大会",
        "id": "memo_36_5"
      }
    ],
    "total": 10
  },
  "inspirations": {
    "items": [
      {
        "date": "6月24日",
        "inspiration": "",
        "harvest": "",
        "task": "",
        "mood": "test full range"
      },
      {
        "date": "7月27日",
        "inspiration": "",
        "harvest": "让AI直接读取我的飞书选题表格，做好排期后，让它一键写笔记，不用我再一个个选题发给它们了",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月28日",
        "inspiration": "",
        "harvest": "1.学会了借助skill优化网站\n2.发现了飞书字段有一个【字段捷径中心】，可以把现有字段转换为其他想要的字段形式，比如日期变成年月\n3.把做人生系统个人网站的经验封装成了life-dashboard-builder Skill",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月30日",
        "inspiration": "",
        "harvest": "",
        "task": "1.挂周一的号-北京妇产医院\n2.买山药粉\n3.做鸡肉干",
        "mood": ""
      },
      {
        "date": "7月31日",
        "inspiration": "",
        "harvest": "孕期知识库是我的第一个产品，不一定是我人生唯一产品",
        "task": "1.买山药粉\n2.确认一下 AI 资讯数据来源和已发布笔记数据是否正确",
        "mood": ""
      },
      {
        "date": "8月1日",
        "inspiration": "",
        "harvest": "",
        "task": "1.和杜爽爽视频\n2.调研一下爆款笔记，关键词：生育、成为妈妈、怀孕",
        "mood": ""
      },
      {
        "date": "8月3日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.把我的人生系统这个网站做一下优化迭代",
        "mood": ""
      },
      {
        "date": "8月5日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材\n3.扫地",
        "mood": ""
      },
      {
        "date": "8月6日",
        "inspiration": "",
        "harvest": "1.实拍图生图步骤，尽量和 AI 一个系列一个系列的做，而不是一次性做几种风格\n2.写了就发的网站作图很方便，但是容易被系统判为 AI 创作，暂时先不用。",
        "task": "",
        "mood": ""
      },
      {
        "date": "8月7日",
        "inspiration": "",
        "harvest": "",
        "task": "找之前的排卵监测报告，看内膜长的情况\n看不二的个人网站，学习一下\n把这台 Mac 的数据都迁移到新 Mac，以后用新 Mac",
        "mood": ""
      },
      {
        "date": "8月10日",
        "inspiration": "",
        "harvest": "",
        "task": "晚上给杜爽爽视频问国庆要不要去马来西亚\n吃一盒酸奶+苹果桃子",
        "mood": ""
      },
      {
        "date": "8月12日",
        "inspiration": "",
        "harvest": "",
        "task": "缴7月社保",
        "mood": ""
      },
      {
        "date": "8月14日",
        "inspiration": "",
        "harvest": "",
        "task": "不做好物博主，看看是阿佳呀、水北山南的账号",
        "mood": ""
      }
    ],
    "last_updated": "6月24日",
    "today_updated": false
  },
  "finance": {
    "year_income": "¥595,774",
    "year_expense": "¥236,821",
    "monthly_data": [
      {
        "month": "2026年1月",
        "income": 91873.0,
        "expense": 29618.52
      },
      {
        "month": "2026年2月",
        "income": 39100.0,
        "expense": 46365.75
      },
      {
        "month": "2026年3月",
        "income": 37290.86,
        "expense": 40501.47
      },
      {
        "month": "2026年4月",
        "income": 39337.92,
        "expense": 40147.7
      },
      {
        "month": "2026年5月",
        "income": 276369.07,
        "expense": 29135.81
      },
      {
        "month": "2026年6月",
        "income": 33091.87,
        "expense": 27747.77
      }
    ],
    "yesterday_expense": "¥0.00",
    "last_updated": "2026-08-17",
    "last_month_expense": "¥23,304.58",
    "last_month_income": "¥34,711.87",
    "month_expense_to_yesterday": "¥5480.31",
    "income_annual": 24973,
    "income_ytd": 24973.0,
    "current_month_expense": "¥5499.11"
  },
  "reading": {
    "challenge_days": 162,
    "challenge_target": 365,
    "rolling_day": 162,
    "total_days": 1121,
    "weekly_read_time": 16,
    "yesterday_read_time": 3,
    "total_read_hours": 458,
    "total_read_books": 150,
    "currently_reading": [
      {
        "title": "听段涛聊孕事",
        "author": "段涛",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-17",
        "created": "2026-08-17"
      },
      {
        "title": "荷马史诗《伊利亚特》（罗念生全集·第六卷）",
        "author": "[古希腊]荷马",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-17",
        "created": "2026-08-17"
      },
      {
        "title": "诊疗椅上的谎言",
        "author": "[美]欧文·亚隆",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-06",
        "created": "2026-08-06"
      },
      {
        "title": "动机心理学",
        "author": "[美]爱德华·伯克利  [美]梅利莎·伯克利",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-06",
        "created": "2026-08-06"
      },
      {
        "title": "我怎么这么会当妈",
        "author": "格十三",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-01",
        "created": "2026-08-01"
      }
    ],
    "medals": [
      {
        "id": "M7-0-200",
        "type": 7,
        "subtype": 0,
        "level": 200,
        "ctime": 1783829092,
        "atime": 1783839061,
        "rank": 644409,
        "users": 654234,
        "hint": "想法发布 200 条",
        "renderItem": "07 / 12",
        "name": "想法发布",
        "index": 0,
        "availableCond": "累积达到200条",
        "tip": "再发表 0 条想法可得",
        "title": "想法发布",
        "rankText": "第644409位获得此勋章的书友",
        "displayText": "想法发布 200 条"
      },
      {
        "id": "M1-0-90",
        "type": 1,
        "subtype": 0,
        "level": 90,
        "ctime": 1778297612,
        "atime": 1778297636,
        "rank": 1894417,
        "users": 1937823,
        "hint": "连续阅读 90 天",
        "renderItem": "05 / 09",
        "name": "连续阅读",
        "index": 1,
        "availableCond": "累积达到90天",
        "tip": "再连续阅读 89 天可得",
        "title": "连续阅读",
        "rankText": "第1894417位获得此勋章的书友",
        "displayText": "连续阅读 90 天"
      },
      {
        "id": "M12-2-3-I-0-0-0",
        "type": 12,
        "subtype": 2,
        "level": 0,
        "ctime": 1776906259,
        "atime": 1776906259,
        "rank": 102178,
        "users": 472590,
        "hint": "你与华夏的文字格外投缘",
        "renderItem": "04 / 23",
        "name": "世界读书日",
        "index": 2,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "世界读书日",
        "rankText": "第102178位获得此勋章的书友",
        "displayText": "山水行吟客",
        "styleType": 1,
        "styleTitle": "山水行吟客",
        "styleDesc": "你与华夏的文字格外投缘"
      },
      {
        "id": "M3-0-1000",
        "type": 3,
        "subtype": 0,
        "level": 1000,
        "ctime": 1776347296,
        "atime": 1776347477,
        "rank": 1755752,
        "users": 1811585,
        "hint": "阅读 1000 天",
        "renderItem": "04 / 16",
        "name": "阅读天数",
        "index": 3,
        "availableCond": "累积达到1000天",
        "tip": "再阅读 0 天可得",
        "title": "阅读天数",
        "rankText": "第1755752位获得此勋章的书友",
        "displayText": "阅读 1000 天"
      },
      {
        "id": "M15-2-0",
        "type": 15,
        "subtype": 2,
        "level": 0,
        "ctime": 1774972748,
        "atime": 1774972748,
        "rank": 697853,
        "users": 803296,
        "hint": "21天阅读挑战",
        "renderItem": "03 / 31",
        "name": "21天阅读挑战",
        "index": 4,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "21天阅读挑战",
        "rankText": "成功挑战2次 · 第697853位获得此勋章的书友",
        "displayText": "21天阅读挑战"
      }
    ],
    "last_updated": "2026-08-17",
    "total_finished_books": 65,
    "weekly_data": {
      "weekly_read_time": 16,
      "yesterday_read_time": 3,
      "source": "周数据"
    },
    "total_data": {
      "total_read_hours": 458,
      "total_read_books": 150,
      "total_finished_books": 65,
      "source": "总数据"
    }
  },
  "published_notes": {
    "total": 140,
    "last_updated": "2026-08-17",
    "month_count": 29
  },
  "exercise": {
    "month": "2026年7月",
    "month_key": "2026-07",
    "month_label": "7月",
    "week_header": [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "日"
    ],
    "exercise_blocks": [
      {
        "emoji": "🧘",
        "name": "体态矫正",
        "color": "#FF6B9D",
        "videos": [
          {
            "title": "【欧阳春晓】15min告别肩背肥厚",
            "bvid": "BV1Qv411t7EN",
            "duration": "15:00"
          },
          {
            "title": "MIZI · 改善圆肩驼背｜跟练版",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "12:00"
          },
          {
            "title": "骨盆前倾矫正｜每天10分钟",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          }
        ]
      },
      {
        "emoji": "🔥",
        "name": "燃脂训练",
        "color": "#FF9F43",
        "videos": [
          {
            "title": "帕梅拉 · 15min全身燃脂｜暴汗",
            "bvid": "BV1qK4y1t7fP",
            "duration": "15:00"
          },
          {
            "title": "Eleni Fit · 30min站立燃脂｜新手友好",
            "bvid": "BV1GJ411x7h7",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 14天瘦大腿内侧｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "28:00"
          }
        ]
      },
      {
        "emoji": "💪",
        "name": "力量塑形",
        "color": "#4ECDC4",
        "videos": [
          {
            "title": "蜜桃臀养成 · 31min跟练版",
            "bvid": "BV1GJ411x7h7",
            "duration": "31:00"
          },
          {
            "title": "Barre · 30min肩背塑形",
            "bvid": "BV1qK4y1t7fP",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 2周瘦手臂｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "21:00"
          }
        ]
      },
      {
        "emoji": "🫁",
        "name": "拉伸放松",
        "color": "#A29BFE",
        "videos": [
          {
            "title": "全身拉伸放松 · 10min",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          },
          {
            "title": "腿部拉伸 · 睡前10min",
            "bvid": "BV1qK4y1t7fP",
            "duration": "10:00"
          },
          {
            "title": "阴瑜伽 · 放松30min",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "30:00"
          }
        ]
      }
    ]
  },
  "oneCompany": {
    "total_revenue": "¥279.6",
    "total_orders": 14,
    "products": [
      {
        "name": "新手妈妈孕期必备知识库｜0-40周全阶段｜第一次怀孕+焦虑型妈妈",
        "price": "¥39.9"
      },
      {
        "name": "第一次怀孕安心决策系统｜0-40周遇到问题不慌知道下一步怎么办",
        "price": "¥39.9"
      },
      {
        "name": "准妈妈0-40周孕期安心知识库｜从怀孕到分娩的安心决策工具",
        "price": "¥39.9"
      },
      {
        "name": "流产后身心恢复指南｜身心重建+饮食调理+备孕指导+伴侣沟通",
        "price": "¥9.9"
      }
    ],
    "total_published_notes": 140,
    "monthly_revenue": [],
    "weekly_revenue": [
      {
        "label": "7/13",
        "revenue": 49.8
      },
      {
        "label": "7/20",
        "revenue": 0
      },
      {
        "label": "7/27",
        "revenue": 6.9
      },
      {
        "label": "8/3",
        "revenue": 79.8
      },
      {
        "label": "8/10",
        "revenue": 0
      },
      {
        "label": "8/17",
        "revenue": 0
      }
    ],
    "last_updated": "2026-08-17"
  },
  "hotTopics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 白带答疑：性生活后变多？变黄？异味儿？瘙痒？口服益生菌？|Vol.175",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "3天前"
      },
      {
        "title": "🎙 嗨咻 | 101.跟桂律师聊天｜为什么感情越好，越该把钱说清楚？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "5天前"
      },
      {
        "title": "🎙 头回当妈 | 101.经典回顾｜中西方带娃理念禁忌大比拼",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 畅所育言 | 112在大理，做个不敷衍孩子和自己的大人｜两个妈妈夏令营复盘",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 Alison Yu心理 | ep91 | 如何找回自己的勇气和力量，走出气馁",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "今天"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-08-17",
    "ai_news": [
      {
        "title": "Qwen 3.8 27B 表现出色，但默认推理强度过高导致过度思考",
        "url": "https://aihot.virxact.com/items/cmswesk6a0r2hrovml2edcl2c",
        "published": "Sun, 16 Aug 2026 22:00:39 GMT",
        "source": "Simon Willison 博客",
        "time_ago": "今天"
      },
      {
        "title": "新兴多智能体系统的模式与问题",
        "url": "https://aihot.virxact.com/items/cmsvptx2m061frovmjoavsi0l",
        "published": "Sun, 16 Aug 2026 11:17:57 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "昨天"
      },
      {
        "title": "Cursor 正式被 SpaceX 收购",
        "url": "https://aihot.virxact.com/items/cmsuto7hk0912rouhodiiywlk",
        "published": "Sat, 15 Aug 2026 20:05:54 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "昨天"
      },
      {
        "title": "AI生成书籍正淹没亚马逊，并拉低人类作者的单书收入",
        "url": "https://aihot.virxact.com/items/cmsuaf2hr05zgroe0y1e7275v",
        "published": "Sat, 15 Aug 2026 11:00:50 GMT",
        "source": "The Decoder：AI News（RSS）",
        "time_ago": "2天前"
      },
      {
        "title": "Gemini 3.7 Flash 全面上线 Pro 与 Ultra 用户",
        "url": "https://aihot.virxact.com/items/cmst9yj3c05utrodz443l0odv",
        "published": "Fri, 14 Aug 2026 18:06:29 GMT",
        "source": "X：Gemini (@GeminiApp)",
        "time_ago": "3天前"
      },
      {
        "title": "通义千问开源 Qwen3.8 系列模型",
        "url": "https://aihot.virxact.com/items/cmst3j53e03ncro068tgsr4xn",
        "published": "Fri, 14 Aug 2026 15:02:48 GMT",
        "source": "X：通义千问 / Qwen (@Alibaba_Qwen)",
        "time_ago": "3天前"
      },
      {
        "title": "OpenAI and Anthropic in price war as Chinese AI rivals gain ground",
        "url": "https://aihot.virxact.com/items/cmst2gs6d02lmro06sb7as7av",
        "published": "Fri, 14 Aug 2026 14:27:14 GMT",
        "source": "Ars Technica：AI（RSS）",
        "time_ago": "3天前"
      },
      {
        "title": "dots3-note Preview 开源：280B 参数轻量模型，主打长程智能体与多模态推理",
        "url": "https://aihot.virxact.com/items/cmssv94cg0h4mroffsb9e7a88",
        "published": "Fri, 14 Aug 2026 11:25:29 GMT",
        "source": "公众号：小红书技术（dots.llm）",
        "time_ago": "3天前"
      },
      {
        "title": "GLM-5.3 发布：编程能力开源第一，并涌现网络安全能力",
        "url": "https://aihot.virxact.com/items/cmswlcuwb0wcyrovmfccplna7",
        "published": "Fri, 14 Aug 2026 06:00:00 GMT",
        "source": "智谱：研究（网页内嵌数据）",
        "time_ago": "3天前"
      }
    ],
    "one_company_news": [
      {
        "title": "AI订单涌入，万国数据上调全年业绩指引，今年投100亿元扩建数据中心｜看财报",
        "url": "https://www.tmtpost.com/8105732.html",
        "published": "Mon, 17 Aug 2026 18:29:05 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "被 AI 碾压 30 年后，人们重新爱上了下棋",
        "url": "http://www.geekpark.net/news/368897",
        "published": "Mon, 17 Aug 2026 13:54:45 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "22.39 万元起，岚图追光 S 上市，大回环是噱头，运动底盘才是正题",
        "url": "https://www.ifanr.com/1675423?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Mon, 17 Aug 2026 09:57:19 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "last_sync": "2026-08-17 18:40",
  "expense_categories": {
    "items": [
      {
        "rank": 1,
        "category": "房贷",
        "emoji": "🏠",
        "amount": "¥7,927",
        "amount_raw": 7927.4,
        "percent": 100
      },
      {
        "rank": 2,
        "category": "房租",
        "emoji": "🏠",
        "amount": "¥4,530",
        "amount_raw": 4530.0,
        "percent": 57
      },
      {
        "rank": 3,
        "category": "赵晗支出",
        "emoji": "👤",
        "amount": "¥3,518",
        "amount_raw": 3518.07,
        "percent": 44
      },
      {
        "rank": 4,
        "category": "固定支出",
        "emoji": "🔒",
        "amount": "¥2,667",
        "amount_raw": 2667.27,
        "percent": 34
      },
      {
        "rank": 5,
        "category": "公交打车",
        "emoji": "📌",
        "amount": "¥1,266",
        "amount_raw": 1266.0700000000002,
        "percent": 16
      },
      {
        "rank": 6,
        "category": "零食奶茶",
        "emoji": "📌",
        "amount": "¥926",
        "amount_raw": 926.73,
        "percent": 12
      },
      {
        "rank": 7,
        "category": "一日三餐",
        "emoji": "🍽️",
        "amount": "¥884",
        "amount_raw": 884.7199999999999,
        "percent": 11
      }
    ],
    "month": "2026年7月",
    "last_updated": "2026-08-17"
  },
  "hot_topics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 白带答疑：性生活后变多？变黄？异味儿？瘙痒？口服益生菌？|Vol.175",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "3天前"
      },
      {
        "title": "🎙 嗨咻 | 101.跟桂律师聊天｜为什么感情越好，越该把钱说清楚？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "5天前"
      },
      {
        "title": "🎙 头回当妈 | 101.经典回顾｜中西方带娃理念禁忌大比拼",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 畅所育言 | 112在大理，做个不敷衍孩子和自己的大人｜两个妈妈夏令营复盘",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 Alison Yu心理 | ep91 | 如何找回自己的勇气和力量，走出气馁",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "今天"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-08-17",
    "ai_news": [
      {
        "title": "Qwen 3.8 27B 表现出色，但默认推理强度过高导致过度思考",
        "url": "https://aihot.virxact.com/items/cmswesk6a0r2hrovml2edcl2c",
        "published": "Sun, 16 Aug 2026 22:00:39 GMT",
        "source": "Simon Willison 博客",
        "time_ago": "今天"
      },
      {
        "title": "新兴多智能体系统的模式与问题",
        "url": "https://aihot.virxact.com/items/cmsvptx2m061frovmjoavsi0l",
        "published": "Sun, 16 Aug 2026 11:17:57 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "昨天"
      },
      {
        "title": "Cursor 正式被 SpaceX 收购",
        "url": "https://aihot.virxact.com/items/cmsuto7hk0912rouhodiiywlk",
        "published": "Sat, 15 Aug 2026 20:05:54 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "昨天"
      },
      {
        "title": "AI生成书籍正淹没亚马逊，并拉低人类作者的单书收入",
        "url": "https://aihot.virxact.com/items/cmsuaf2hr05zgroe0y1e7275v",
        "published": "Sat, 15 Aug 2026 11:00:50 GMT",
        "source": "The Decoder：AI News（RSS）",
        "time_ago": "2天前"
      },
      {
        "title": "Gemini 3.7 Flash 全面上线 Pro 与 Ultra 用户",
        "url": "https://aihot.virxact.com/items/cmst9yj3c05utrodz443l0odv",
        "published": "Fri, 14 Aug 2026 18:06:29 GMT",
        "source": "X：Gemini (@GeminiApp)",
        "time_ago": "3天前"
      },
      {
        "title": "通义千问开源 Qwen3.8 系列模型",
        "url": "https://aihot.virxact.com/items/cmst3j53e03ncro068tgsr4xn",
        "published": "Fri, 14 Aug 2026 15:02:48 GMT",
        "source": "X：通义千问 / Qwen (@Alibaba_Qwen)",
        "time_ago": "3天前"
      },
      {
        "title": "OpenAI and Anthropic in price war as Chinese AI rivals gain ground",
        "url": "https://aihot.virxact.com/items/cmst2gs6d02lmro06sb7as7av",
        "published": "Fri, 14 Aug 2026 14:27:14 GMT",
        "source": "Ars Technica：AI（RSS）",
        "time_ago": "3天前"
      },
      {
        "title": "dots3-note Preview 开源：280B 参数轻量模型，主打长程智能体与多模态推理",
        "url": "https://aihot.virxact.com/items/cmssv94cg0h4mroffsb9e7a88",
        "published": "Fri, 14 Aug 2026 11:25:29 GMT",
        "source": "公众号：小红书技术（dots.llm）",
        "time_ago": "3天前"
      },
      {
        "title": "GLM-5.3 发布：编程能力开源第一，并涌现网络安全能力",
        "url": "https://aihot.virxact.com/items/cmswlcuwb0wcyrovmfccplna7",
        "published": "Fri, 14 Aug 2026 06:00:00 GMT",
        "source": "智谱：研究（网页内嵌数据）",
        "time_ago": "3天前"
      }
    ],
    "one_company_news": [
      {
        "title": "AI订单涌入，万国数据上调全年业绩指引，今年投100亿元扩建数据中心｜看财报",
        "url": "https://www.tmtpost.com/8105732.html",
        "published": "Mon, 17 Aug 2026 18:29:05 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "被 AI 碾压 30 年后，人们重新爱上了下棋",
        "url": "http://www.geekpark.net/news/368897",
        "published": "Mon, 17 Aug 2026 13:54:45 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "22.39 万元起，岚图追光 S 上市，大回环是噱头，运动底盘才是正题",
        "url": "https://www.ifanr.com/1675423?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Mon, 17 Aug 2026 09:57:19 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "weather": {
    "cities": {
      "beijing": {
        "name": "北京 · 顺义",
        "temp": 28.1,
        "weather_code": 3,
        "desc": "☁️ 阴",
        "min": 19.0,
        "max": 30.5
      },
      "wuhan": {
        "name": "武汉 · 洪山",
        "temp": 29.6,
        "weather_code": 2,
        "desc": "⛅ 局部多云",
        "min": 25.4,
        "max": 31.7
      }
    },
    "last_updated": "2026-08-17 18:38"
  },
  "inspirations_done": {
    "task:挂周一的号-北京妇产医院": true,
    "task:买山药粉": true,
    "task:做鸡肉干": true,
    "task:确认一下 AI 资讯数据来源和已发布笔记数据是否正确": true,
    "task:和杜爽爽视频": true,
    "task:调研一下爆款笔记，关键词：生育、成为妈妈、怀孕": true,
    "task:把我的人生系统这个网站做一下优化迭代": true,
    "task:上架新产品，做 3 个 sku": true,
    "task:扫地": true,
    "task:看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材": true,
    "task:缴7月社保": true
  }
};
