// Auto-generated by feishu_sync.py
// Last updated: 2026-09-08 12:58
window.DASHBOARD_DATA = {
  "tasks": {
    "date": "9月8日",
    "items": [
      {
        "text": "去医院检查看内膜生长情况",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "做2篇IP号笔记的图片",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "做3篇拆解笔记的图片",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "思考新的备孕选题",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "拍一下好物照片，定一下场景",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "运动1小时",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_text": "1.去医院检查看内膜生长情况\n2.做2篇IP号笔记的图片\n3.做3篇拆解笔记的图片\n4.思考新的备孕选题\n5.拍一下好物照片，定一下场景\n6.运动1小时",
    "tasks": [
      {
        "text": "去医院检查看内膜生长情况",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "做2篇IP号笔记的图片",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "做3篇拆解笔记的图片",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "思考新的备孕选题",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "拍一下好物照片，定一下场景",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "运动1小时",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_tasks_text": "1.去医院检查看内膜生长情况\n2.做2篇IP号笔记的图片\n3.做3篇拆解笔记的图片\n4.思考新的备孕选题\n5.拍一下好物照片，定一下场景\n6.运动1小时"
  },
  "memos": {
    "items": [
      {
        "date": "9月2日",
        "text": "每次做选题，最多10条，太多了后面都会变化没必要，可以收集但是没必要一下子做太多。",
        "id": "memo_69_0"
      },
      {
        "date": "8月28日",
        "text": "怀孕后开始写「孕期周记」",
        "id": "memo_66_0"
      },
      {
        "date": "8月24日",
        "text": "好物账号发布时间：工作日下午 4-6 点、晚上 8 点、上午10-11点",
        "id": "memo_62_0"
      },
      {
        "date": "8月17日",
        "text": "拆解博主不是目的是工具，最终是要做好物博主",
        "id": "memo_55_0"
      },
      {
        "date": "8月15日",
        "text": "试管容易违规，尽量不讲",
        "id": "memo_53_0"
      },
      {
        "date": "8月5日",
        "text": "workbuddy的一人公司专家团用一下",
        "id": "memo_44_2"
      },
      {
        "date": "8月5日",
        "text": "小红书虚拟产品定位skill用一下",
        "id": "memo_44_1"
      },
      {
        "date": "8月5日",
        "text": "开发【嘎嘎有用】生活小程序",
        "id": "memo_44_0"
      },
      {
        "date": "7月31日",
        "text": "买个摄像头回家（放客厅看爸妈小耳朵）",
        "id": "memo_39_0"
      },
      {
        "date": "7月29日",
        "text": "流产后身心恢复指南，卖的更好，是不是可以继续开发类似的产品",
        "id": "memo_37_1"
      }
    ],
    "total": 10
  },
  "inspirations": {
    "items": [
      {
        "date": "6月24日",
        "inspiration": "",
        "harvest": "",
        "task": "",
        "mood": "test full range"
      },
      {
        "date": "7月27日",
        "inspiration": "",
        "harvest": "让AI直接读取我的飞书选题表格，做好排期后，让它一键写笔记，不用我再一个个选题发给它们了",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月28日",
        "inspiration": "",
        "harvest": "1.学会了借助skill优化网站\n2.发现了飞书字段有一个【字段捷径中心】，可以把现有字段转换为其他想要的字段形式，比如日期变成年月\n3.把做人生系统个人网站的经验封装成了life-dashboard-builder Skill",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月30日",
        "inspiration": "",
        "harvest": "",
        "task": "1.挂周一的号-北京妇产医院\n2.买山药粉\n3.做鸡肉干",
        "mood": ""
      },
      {
        "date": "7月31日",
        "inspiration": "",
        "harvest": "孕期知识库是我的第一个产品，不一定是我人生唯一产品",
        "task": "1.买山药粉\n2.确认一下 AI 资讯数据来源和已发布笔记数据是否正确",
        "mood": ""
      },
      {
        "date": "8月1日",
        "inspiration": "",
        "harvest": "",
        "task": "1.和杜爽爽视频\n2.调研一下爆款笔记，关键词：生育、成为妈妈、怀孕",
        "mood": ""
      },
      {
        "date": "8月3日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.把我的人生系统这个网站做一下优化迭代",
        "mood": ""
      },
      {
        "date": "8月5日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材\n3.扫地",
        "mood": ""
      },
      {
        "date": "8月6日",
        "inspiration": "",
        "harvest": "1.实拍图生图步骤，尽量和 AI 一个系列一个系列的做，而不是一次性做几种风格\n2.写了就发的网站作图很方便，但是容易被系统判为 AI 创作，暂时先不用。",
        "task": "",
        "mood": ""
      },
      {
        "date": "8月7日",
        "inspiration": "",
        "harvest": "",
        "task": "找之前的排卵监测报告，看内膜长的情况\n看不二的个人网站，学习一下\n把这台 Mac 的数据都迁移到新 Mac，以后用新 Mac",
        "mood": ""
      },
      {
        "date": "8月10日",
        "inspiration": "",
        "harvest": "",
        "task": "晚上给杜爽爽视频问国庆要不要去马来西亚\n吃一盒酸奶+苹果桃子",
        "mood": ""
      },
      {
        "date": "8月12日",
        "inspiration": "",
        "harvest": "",
        "task": "缴7月社保",
        "mood": ""
      },
      {
        "date": "8月14日",
        "inspiration": "",
        "harvest": "",
        "task": "不做好物博主，看看是阿佳呀、水北山南的账号",
        "mood": ""
      },
      {
        "date": "8月20日",
        "inspiration": "",
        "harvest": "",
        "task": "用湿纸巾擦一下几个白色桌面",
        "mood": ""
      },
      {
        "date": "8月21日",
        "inspiration": "",
        "harvest": "",
        "task": "1.用湿纸巾擦一下几个白色桌面\n2.拖地\n3.看赵晗一个月流量情况\n4.重新调整几张电话卡\n5.等三个账号稳步运行后，用 AI 做一个自媒体工作台",
        "mood": ""
      },
      {
        "date": "8月24日",
        "inspiration": "",
        "harvest": "",
        "task": "1.盘点现有的好物，做分类，后面就可以根据现有产品做好物选题",
        "mood": ""
      },
      {
        "date": "8月27日",
        "inspiration": "",
        "harvest": "",
        "task": "1.给妹妹看一下生日礼物要买了",
        "mood": ""
      },
      {
        "date": "9月2日",
        "inspiration": "",
        "harvest": "",
        "task": "1.写5篇博主拆解笔记",
        "mood": ""
      },
      {
        "date": "9月3日",
        "inspiration": "",
        "harvest": "",
        "task": "1.写5篇博主拆解笔记",
        "mood": ""
      }
    ],
    "last_updated": "6月24日",
    "today_updated": false
  },
  "finance": {
    "year_income": "¥595,774",
    "year_expense": "¥274,432",
    "monthly_data": [
      {
        "month": "2026年1月",
        "income": 91873.0,
        "expense": 29618.52
      },
      {
        "month": "2026年2月",
        "income": 39100.0,
        "expense": 46365.75
      },
      {
        "month": "2026年3月",
        "income": 37290.86,
        "expense": 40501.47
      },
      {
        "month": "2026年4月",
        "income": 39337.92,
        "expense": 40147.7
      },
      {
        "month": "2026年5月",
        "income": 276369.07,
        "expense": 29135.81
      },
      {
        "month": "2026年6月",
        "income": 33091.87,
        "expense": 27747.77
      }
    ],
    "yesterday_expense": "¥179.47",
    "last_updated": "2026-09-08",
    "last_month_expense": "¥37,610.89",
    "last_month_income": "¥44,000.00",
    "month_expense_to_yesterday": "¥12234.87",
    "income_annual": 24973,
    "income_ytd": 24973.0,
    "current_month_expense": "¥12298.03"
  },
  "reading": {
    "challenge_days": 184,
    "challenge_target": 365,
    "rolling_day": 184,
    "total_days": 1143,
    "weekly_read_time": 36,
    "yesterday_read_time": 19,
    "total_read_hours": 469,
    "total_read_books": 155,
    "currently_reading": [
      {
        "title": "李诞工作手册（万字全新增订）",
        "author": "李诞",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-09-08",
        "created": "2026-09-08"
      },
      {
        "title": "略萨作品：酒吧长谈（精装珍藏版）",
        "author": "马里奥·巴尔加斯·略萨",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-09-06",
        "created": "2026-09-06"
      },
      {
        "title": "无条件养育",
        "author": "艾尔菲·科恩",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-09-05",
        "created": "2026-09-05"
      },
      {
        "title": "自我关怀的力量",
        "author": "克里斯廷·内夫",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-09-04",
        "created": "2026-09-04"
      },
      {
        "title": "婚姻与爱情（杜素娟伴读）",
        "author": "[英]伯特兰·罗素",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-09-03",
        "created": "2026-09-03"
      }
    ],
    "medals": [
      {
        "id": "M7-0-200",
        "type": 7,
        "subtype": 0,
        "level": 200,
        "ctime": 1783829092,
        "atime": 1783839061,
        "rank": 644409,
        "users": 659782,
        "hint": "想法发布 200 条",
        "renderItem": "07 / 12",
        "name": "想法发布",
        "index": 0,
        "availableCond": "累积达到200条",
        "tip": "再发表 0 条想法可得",
        "title": "想法发布",
        "rankText": "第644409位获得此勋章的书友",
        "displayText": "想法发布 200 条"
      },
      {
        "id": "M1-0-90",
        "type": 1,
        "subtype": 0,
        "level": 90,
        "ctime": 1778297612,
        "atime": 1778297636,
        "rank": 1894417,
        "users": 1946596,
        "hint": "连续阅读 90 天",
        "renderItem": "05 / 09",
        "name": "连续阅读",
        "index": 1,
        "availableCond": "累积达到90天",
        "tip": "再连续阅读 67 天可得",
        "title": "连续阅读",
        "rankText": "第1894417位获得此勋章的书友",
        "displayText": "连续阅读 90 天"
      },
      {
        "id": "M12-2-3-I-0-0-0",
        "type": 12,
        "subtype": 2,
        "level": 0,
        "ctime": 1776906259,
        "atime": 1776906259,
        "rank": 102178,
        "users": 472590,
        "hint": "你与华夏的文字格外投缘",
        "renderItem": "04 / 23",
        "name": "世界读书日",
        "index": 2,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "世界读书日",
        "rankText": "第102178位获得此勋章的书友",
        "displayText": "山水行吟客",
        "styleType": 1,
        "styleTitle": "山水行吟客",
        "styleDesc": "你与华夏的文字格外投缘"
      },
      {
        "id": "M3-0-1000",
        "type": 3,
        "subtype": 0,
        "level": 1000,
        "ctime": 1776347296,
        "atime": 1776347477,
        "rank": 1755752,
        "users": 1821022,
        "hint": "阅读 1000 天",
        "renderItem": "04 / 16",
        "name": "阅读天数",
        "index": 3,
        "availableCond": "累积达到1000天",
        "tip": "再阅读 0 天可得",
        "title": "阅读天数",
        "rankText": "第1755752位获得此勋章的书友",
        "displayText": "阅读 1000 天"
      },
      {
        "id": "M15-2-0",
        "type": 15,
        "subtype": 2,
        "level": 0,
        "ctime": 1774972748,
        "atime": 1774972748,
        "rank": 697853,
        "users": 818683,
        "hint": "21天阅读挑战",
        "renderItem": "03 / 31",
        "name": "21天阅读挑战",
        "index": 4,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "21天阅读挑战",
        "rankText": "成功挑战2次 · 第697853位获得此勋章的书友",
        "displayText": "21天阅读挑战"
      }
    ],
    "last_updated": "2026-09-08",
    "total_finished_books": 68,
    "weekly_data": {
      "weekly_read_time": 36,
      "yesterday_read_time": 19,
      "source": "周数据"
    },
    "total_data": {
      "total_read_hours": 469,
      "total_read_books": 155,
      "total_finished_books": 68,
      "source": "总数据"
    }
  },
  "published_notes": {
    "total": 160,
    "last_updated": "2026-09-08",
    "month_count": 3
  },
  "exercise": {
    "month": "2026年7月",
    "month_key": "2026-07",
    "month_label": "7月",
    "week_header": [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "日"
    ],
    "exercise_blocks": [
      {
        "emoji": "🧘",
        "name": "体态矫正",
        "color": "#FF6B9D",
        "videos": [
          {
            "title": "【欧阳春晓】15min告别肩背肥厚",
            "bvid": "BV1Qv411t7EN",
            "duration": "15:00"
          },
          {
            "title": "MIZI · 改善圆肩驼背｜跟练版",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "12:00"
          },
          {
            "title": "骨盆前倾矫正｜每天10分钟",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          }
        ]
      },
      {
        "emoji": "🔥",
        "name": "燃脂训练",
        "color": "#FF9F43",
        "videos": [
          {
            "title": "帕梅拉 · 15min全身燃脂｜暴汗",
            "bvid": "BV1qK4y1t7fP",
            "duration": "15:00"
          },
          {
            "title": "Eleni Fit · 30min站立燃脂｜新手友好",
            "bvid": "BV1GJ411x7h7",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 14天瘦大腿内侧｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "28:00"
          }
        ]
      },
      {
        "emoji": "💪",
        "name": "力量塑形",
        "color": "#4ECDC4",
        "videos": [
          {
            "title": "蜜桃臀养成 · 31min跟练版",
            "bvid": "BV1GJ411x7h7",
            "duration": "31:00"
          },
          {
            "title": "Barre · 30min肩背塑形",
            "bvid": "BV1qK4y1t7fP",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 2周瘦手臂｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "21:00"
          }
        ]
      },
      {
        "emoji": "🫁",
        "name": "拉伸放松",
        "color": "#A29BFE",
        "videos": [
          {
            "title": "全身拉伸放松 · 10min",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          },
          {
            "title": "腿部拉伸 · 睡前10min",
            "bvid": "BV1qK4y1t7fP",
            "duration": "10:00"
          },
          {
            "title": "阴瑜伽 · 放松30min",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "30:00"
          }
        ]
      }
    ]
  },
  "oneCompany": {
    "total_revenue": "¥289.5",
    "total_orders": 15,
    "products": [
      {
        "name": "['新手妈妈孕期必备知识库｜0-40周全阶段｜第一次怀孕+焦虑型妈妈']",
        "price": "¥39.9"
      },
      {
        "name": "['第一次怀孕安心决策系统｜0-40周遇到问题不慌知道下一步怎么办']",
        "price": "¥39.9"
      },
      {
        "name": "['准妈妈0-40周孕期安心知识库｜从怀孕到分娩的安心决策工具']",
        "price": "¥39.9"
      },
      {
        "name": "['流产后身心恢复指南｜身心重建+饮食调理+备孕指导+伴侣沟通']",
        "price": "¥9.9"
      }
    ],
    "total_published_notes": 160,
    "monthly_revenue": [],
    "weekly_revenue": [
      {
        "label": "8/3",
        "revenue": 79.8
      },
      {
        "label": "8/10",
        "revenue": 9.9
      },
      {
        "label": "8/17",
        "revenue": 0
      },
      {
        "label": "8/24",
        "revenue": 0
      },
      {
        "label": "8/31",
        "revenue": 0
      },
      {
        "label": "9/7",
        "revenue": 0
      }
    ],
    "last_updated": "2026-09-08"
  },
  "hotTopics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 成年人的「发疯文学」：我们应该如何直面冲突？|声音胶囊01|Vol.178",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "4天前"
      },
      {
        "title": "🎙 嗨咻 | 105. 人到中年，又累又不快乐",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "3天前"
      },
      {
        "title": "🎙 头回当妈 | 102.不造神不鸡娃，顶尖数学家身上的非典型育儿启示",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 畅所育言 | 114《为父则刚》：不是“我帮你带娃”，而是我们一起成为父母｜新晋待产包必备好物",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 Alison Yu心理 | 社会化：我们拥有比自己想象中更多的选择",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-09-08",
    "ai_news": [
      {
        "title": "GPT-6 Astra操控Blender保姆级教程：三种玩法与踩坑实录",
        "url": "https://aihot.virxact.com/items/cmtrxbv5n02etroftlb6u96xt",
        "published": "Tue, 08 Sep 2026 00:17:23 GMT",
        "source": "公众号：数字生命卡兹克",
        "time_ago": "今天"
      },
      {
        "title": "Anthropic 据报道签约高达 5170 亿美元算力协议，锁定至少 14.8 GW 算力",
        "url": "https://aihot.virxact.com/items/cmtrkorpo07jdrotnozlrlyx2",
        "published": "Mon, 07 Sep 2026 18:12:41 GMT",
        "source": "The Decoder：AI News（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "最高法发布涉人工智能纠纷案件审理意见，明确 AI 换脸拟声等裁判规则",
        "url": "https://aihot.virxact.com/items/cmtqy60930445ro7r5nodgoig",
        "published": "Mon, 07 Sep 2026 07:46:08 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "GPT-6 Astra爆火后，卡兹克谈执行能力贬值与判断力断层",
        "url": "https://aihot.virxact.com/items/cmtqhifvf04pwrohqvdfqmfxp",
        "published": "Mon, 07 Sep 2026 00:08:00 GMT",
        "source": "公众号：数字生命卡兹克",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 宣布达到自动化研究实习生里程碑，内部 agent 运行时达人力 3.1 倍",
        "url": "https://aihot.virxact.com/items/cmtq5pxc10275roiufscxyie4",
        "published": "Sun, 06 Sep 2026 18:23:14 GMT",
        "source": "X：Rohan Paul (@rohanpaul_ai)",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 长文阐述对齐与监测困境，称 CoT 监控能力正在减弱",
        "url": "https://aihot.virxact.com/items/cmtq23v6k01aorotwh8xip8r1",
        "published": "Sun, 06 Sep 2026 09:00:00 GMT",
        "source": "OpenAI：官网动态（RSS · 排除企业/客户案例）",
        "time_ago": "2天前"
      },
      {
        "title": "OpenAI 发布内部研究加速报告：已达成自动化研究实习生目标，推进 2028 年 3 月自动化 AI 研究员",
        "url": "https://aihot.virxact.com/items/cmtpzyon6019iroemu68v4s2v",
        "published": "Sun, 06 Sep 2026 08:00:00 GMT",
        "source": "OpenAI：官网动态（RSS · 排除企业/客户案例）",
        "time_ago": "2天前"
      },
      {
        "title": "Fortune 报道 OpenAI 多次修改 GPT-6 Astra 基准测试数据，部分成绩大幅变化",
        "url": "https://aihot.virxact.com/items/cmtphtttc01pkroxxh8pinzq2",
        "published": "Sun, 06 Sep 2026 06:46:16 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "2天前"
      },
      {
        "title": "OpenAI GPT-6 Astra 登顶 Code Arena WebDev 榜首，领先 Claude Fable 5.1 达 35 分",
        "url": "https://aihot.virxact.com/items/cmtoxdsbb032sromz8bcrhsii",
        "published": "Sat, 05 Sep 2026 21:31:52 GMT",
        "source": "X：Testing Catalog (@testingcatalog)",
        "time_ago": "2天前"
      },
      {
        "title": "OpenAI 承认 wiki 事件，称将建立智能体异常行为披露框架",
        "url": "https://aihot.virxact.com/items/cmtoqa3i1022iro4mjh3iogk8",
        "published": "Sat, 05 Sep 2026 18:26:17 GMT",
        "source": "X：Rohan Paul (@rohanpaul_ai)",
        "time_ago": "2天前"
      }
    ],
    "one_company_news": [
      {
        "title": "2026食饮中报观察：“茅五”贡献近半利润，九成公司不再拼增速",
        "url": "https://www.tmtpost.com/8132287.html",
        "published": "Tue, 08 Sep 2026 12:52:00 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "传字节开发实时空间视频生成模型，张一鸣亲自督导；微信内测「AI 社交」功能；华为小米同天发布折叠屏手机",
        "url": "http://www.geekpark.net/news/369965",
        "published": "Tue, 08 Sep 2026 08:34:54 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "AI 开始「互发微信」了，谁来管管它们？| AI 器物志",
        "url": "https://www.ifanr.com/1679104?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Tue, 08 Sep 2026 03:06:24 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "last_sync": "2026-09-08 12:58",
  "expense_categories": {
    "items": [
      {
        "rank": 1,
        "category": "家人朋友",
        "emoji": "📌",
        "amount": "¥9,788",
        "amount_raw": 9788.0,
        "percent": 100
      },
      {
        "rank": 2,
        "category": "房贷",
        "emoji": "🏠",
        "amount": "¥7,927",
        "amount_raw": 7927.4,
        "percent": 81
      },
      {
        "rank": 3,
        "category": "赵晗支出",
        "emoji": "👤",
        "amount": "¥4,990",
        "amount_raw": 4990.37,
        "percent": 51
      },
      {
        "rank": 4,
        "category": "房租",
        "emoji": "🏠",
        "amount": "¥3,800",
        "amount_raw": 3800.0,
        "percent": 39
      },
      {
        "rank": 5,
        "category": "固定支出",
        "emoji": "🔒",
        "amount": "¥2,667",
        "amount_raw": 2667.27,
        "percent": 27
      },
      {
        "rank": 6,
        "category": "买药看病",
        "emoji": "🏥",
        "amount": "¥2,438",
        "amount_raw": 2438.59,
        "percent": 25
      },
      {
        "rank": 7,
        "category": "请客送礼",
        "emoji": "📌",
        "amount": "¥1,465",
        "amount_raw": 1465.49,
        "percent": 15
      }
    ],
    "month": "2026年8月",
    "last_updated": "2026-09-08"
  },
  "hot_topics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 成年人的「发疯文学」：我们应该如何直面冲突？|声音胶囊01|Vol.178",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "4天前"
      },
      {
        "title": "🎙 嗨咻 | 105. 人到中年，又累又不快乐",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "3天前"
      },
      {
        "title": "🎙 头回当妈 | 102.不造神不鸡娃，顶尖数学家身上的非典型育儿启示",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 畅所育言 | 114《为父则刚》：不是“我帮你带娃”，而是我们一起成为父母｜新晋待产包必备好物",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 Alison Yu心理 | 社会化：我们拥有比自己想象中更多的选择",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-09-08",
    "ai_news": [
      {
        "title": "GPT-6 Astra操控Blender保姆级教程：三种玩法与踩坑实录",
        "url": "https://aihot.virxact.com/items/cmtrxbv5n02etroftlb6u96xt",
        "published": "Tue, 08 Sep 2026 00:17:23 GMT",
        "source": "公众号：数字生命卡兹克",
        "time_ago": "今天"
      },
      {
        "title": "Anthropic 据报道签约高达 5170 亿美元算力协议，锁定至少 14.8 GW 算力",
        "url": "https://aihot.virxact.com/items/cmtrkorpo07jdrotnozlrlyx2",
        "published": "Mon, 07 Sep 2026 18:12:41 GMT",
        "source": "The Decoder：AI News（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "最高法发布涉人工智能纠纷案件审理意见，明确 AI 换脸拟声等裁判规则",
        "url": "https://aihot.virxact.com/items/cmtqy60930445ro7r5nodgoig",
        "published": "Mon, 07 Sep 2026 07:46:08 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "GPT-6 Astra爆火后，卡兹克谈执行能力贬值与判断力断层",
        "url": "https://aihot.virxact.com/items/cmtqhifvf04pwrohqvdfqmfxp",
        "published": "Mon, 07 Sep 2026 00:08:00 GMT",
        "source": "公众号：数字生命卡兹克",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 宣布达到自动化研究实习生里程碑，内部 agent 运行时达人力 3.1 倍",
        "url": "https://aihot.virxact.com/items/cmtq5pxc10275roiufscxyie4",
        "published": "Sun, 06 Sep 2026 18:23:14 GMT",
        "source": "X：Rohan Paul (@rohanpaul_ai)",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 长文阐述对齐与监测困境，称 CoT 监控能力正在减弱",
        "url": "https://aihot.virxact.com/items/cmtq23v6k01aorotwh8xip8r1",
        "published": "Sun, 06 Sep 2026 09:00:00 GMT",
        "source": "OpenAI：官网动态（RSS · 排除企业/客户案例）",
        "time_ago": "2天前"
      },
      {
        "title": "OpenAI 发布内部研究加速报告：已达成自动化研究实习生目标，推进 2028 年 3 月自动化 AI 研究员",
        "url": "https://aihot.virxact.com/items/cmtpzyon6019iroemu68v4s2v",
        "published": "Sun, 06 Sep 2026 08:00:00 GMT",
        "source": "OpenAI：官网动态（RSS · 排除企业/客户案例）",
        "time_ago": "2天前"
      },
      {
        "title": "Fortune 报道 OpenAI 多次修改 GPT-6 Astra 基准测试数据，部分成绩大幅变化",
        "url": "https://aihot.virxact.com/items/cmtphtttc01pkroxxh8pinzq2",
        "published": "Sun, 06 Sep 2026 06:46:16 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "2天前"
      },
      {
        "title": "OpenAI GPT-6 Astra 登顶 Code Arena WebDev 榜首，领先 Claude Fable 5.1 达 35 分",
        "url": "https://aihot.virxact.com/items/cmtoxdsbb032sromz8bcrhsii",
        "published": "Sat, 05 Sep 2026 21:31:52 GMT",
        "source": "X：Testing Catalog (@testingcatalog)",
        "time_ago": "2天前"
      },
      {
        "title": "OpenAI 承认 wiki 事件，称将建立智能体异常行为披露框架",
        "url": "https://aihot.virxact.com/items/cmtoqa3i1022iro4mjh3iogk8",
        "published": "Sat, 05 Sep 2026 18:26:17 GMT",
        "source": "X：Rohan Paul (@rohanpaul_ai)",
        "time_ago": "2天前"
      }
    ],
    "one_company_news": [
      {
        "title": "2026食饮中报观察：“茅五”贡献近半利润，九成公司不再拼增速",
        "url": "https://www.tmtpost.com/8132287.html",
        "published": "Tue, 08 Sep 2026 12:52:00 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "传字节开发实时空间视频生成模型，张一鸣亲自督导；微信内测「AI 社交」功能；华为小米同天发布折叠屏手机",
        "url": "http://www.geekpark.net/news/369965",
        "published": "Tue, 08 Sep 2026 08:34:54 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "AI 开始「互发微信」了，谁来管管它们？| AI 器物志",
        "url": "https://www.ifanr.com/1679104?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Tue, 08 Sep 2026 03:06:24 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "weather": {
    "cities": {
      "beijing": {
        "name": "北京 · 顺义",
        "temp": 21.3,
        "weather_code": 3,
        "desc": "☁️ 阴",
        "min": 14.2,
        "max": 22.1
      },
      "wuhan": {
        "name": "武汉 · 洪山",
        "temp": 32.4,
        "weather_code": 1,
        "desc": "🌤 多云",
        "min": 23.6,
        "max": 33.1
      }
    },
    "last_updated": "2026-09-08 12:56"
  },
  "inspirations_done": {
    "task:挂周一的号-北京妇产医院": true,
    "task:买山药粉": true,
    "task:做鸡肉干": true,
    "task:确认一下 AI 资讯数据来源和已发布笔记数据是否正确": true,
    "task:和杜爽爽视频": true,
    "task:调研一下爆款笔记，关键词：生育、成为妈妈、怀孕": true,
    "task:把我的人生系统这个网站做一下优化迭代": true,
    "task:上架新产品，做 3 个 sku": true,
    "task:扫地": true,
    "task:看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材": true,
    "task:缴7月社保": true,
    "task:不做好物博主，看看是阿佳呀、水北山南的账号": true,
    "task:用湿纸巾擦一下几个白色桌面": true,
    "task:拖地": true,
    "task:看赵晗一个月流量情况": true,
    "task:重新调整几张电话卡": true,
    "task:1.盘点现有的好物，做分类，后面就可以根据现有产品做好物选题": true,
    "task:1.给妹妹看一下生日礼物要买了": true,
    "task:等三个账号稳步运行后，用 AI 做一个自媒体工作台": true,
    "task:1.写5篇博主拆解笔记": true
  }
};
