// Auto-generated by feishu_sync.py
// Last updated: 2026-08-25 23:31
window.DASHBOARD_DATA = {
  "tasks": {
    "date": "8月25日",
    "items": [
      {
        "text": "写5篇卖货号笔记，记得有些直接带产品链接",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "梳理一下我目前已有的好物清单",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "做2篇好物拆解笔记（一周3-4更）",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "写3篇 IP 号笔记（以后一周4更）",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "看看ChatGPT 不订阅plus能不能生成我要的图",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "梳理一下现在的工作流和AI配合情况，看看还有哪些地方可以借助AI提升效率",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_text": "1.写5篇卖货号笔记，记得有些直接带产品链接\n2.梳理一下我目前已有的好物清单\n3.做2篇好物拆解笔记（一周3-4更）\n4.写3篇 IP 号笔记（以后一周4更）\n5.看看ChatGPT 不订阅plus能不能生成我要的图\n6.梳理一下现在的工作流和AI配合情况，看看还有哪些地方可以借助AI提升效率",
    "tasks": [
      {
        "text": "写5篇卖货号笔记，记得有些直接带产品链接",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "梳理一下我目前已有的好物清单",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "做2篇好物拆解笔记（一周3-4更）",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "写3篇 IP 号笔记（以后一周4更）",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "看看ChatGPT 不订阅plus能不能生成我要的图",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "梳理一下现在的工作流和AI配合情况，看看还有哪些地方可以借助AI提升效率",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_tasks_text": "1.写5篇卖货号笔记，记得有些直接带产品链接\n2.梳理一下我目前已有的好物清单\n3.做2篇好物拆解笔记（一周3-4更）\n4.写3篇 IP 号笔记（以后一周4更）\n5.看看ChatGPT 不订阅plus能不能生成我要的图\n6.梳理一下现在的工作流和AI配合情况，看看还有哪些地方可以借助AI提升效率"
  },
  "memos": {
    "items": [
      {
        "date": "8月24日",
        "text": "好物账号发布时间：工作日下午 4-6 点、晚上 8 点、上午10-11点",
        "id": "memo_62_0"
      },
      {
        "date": "8月17日",
        "text": "拆解博主不是目的是工具，最终是要做好物博主",
        "id": "memo_55_0"
      },
      {
        "date": "8月15日",
        "text": "试管容易违规，尽量不讲",
        "id": "memo_53_0"
      },
      {
        "date": "8月5日",
        "text": "workbuddy的一人公司专家团用一下",
        "id": "memo_44_2"
      },
      {
        "date": "8月5日",
        "text": "小红书虚拟产品定位skill用一下",
        "id": "memo_44_1"
      },
      {
        "date": "8月5日",
        "text": "开发【嘎嘎有用】生活小程序",
        "id": "memo_44_0"
      },
      {
        "date": "7月31日",
        "text": "买个摄像头回家（放客厅看爸妈小耳朵）",
        "id": "memo_39_0"
      },
      {
        "date": "7月29日",
        "text": "流产后身心恢复指南，卖的更好，是不是可以继续开发类似的产品",
        "id": "memo_37_1"
      },
      {
        "date": "7月29日",
        "text": "孕期记录工作台：用 Workbuddy 搭孕期记录工具，先分享，如果很多人不会用可以打包成 skill 出售",
        "id": "memo_37_0"
      },
      {
        "date": "7月28日",
        "text": "学习红十字会急救培训课程",
        "id": "memo_36_6"
      }
    ],
    "total": 10
  },
  "inspirations": {
    "items": [
      {
        "date": "6月24日",
        "inspiration": "",
        "harvest": "",
        "task": "",
        "mood": "test full range"
      },
      {
        "date": "7月27日",
        "inspiration": "",
        "harvest": "让AI直接读取我的飞书选题表格，做好排期后，让它一键写笔记，不用我再一个个选题发给它们了",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月28日",
        "inspiration": "",
        "harvest": "1.学会了借助skill优化网站\n2.发现了飞书字段有一个【字段捷径中心】，可以把现有字段转换为其他想要的字段形式，比如日期变成年月\n3.把做人生系统个人网站的经验封装成了life-dashboard-builder Skill",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月30日",
        "inspiration": "",
        "harvest": "",
        "task": "1.挂周一的号-北京妇产医院\n2.买山药粉\n3.做鸡肉干",
        "mood": ""
      },
      {
        "date": "7月31日",
        "inspiration": "",
        "harvest": "孕期知识库是我的第一个产品，不一定是我人生唯一产品",
        "task": "1.买山药粉\n2.确认一下 AI 资讯数据来源和已发布笔记数据是否正确",
        "mood": ""
      },
      {
        "date": "8月1日",
        "inspiration": "",
        "harvest": "",
        "task": "1.和杜爽爽视频\n2.调研一下爆款笔记，关键词：生育、成为妈妈、怀孕",
        "mood": ""
      },
      {
        "date": "8月3日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.把我的人生系统这个网站做一下优化迭代",
        "mood": ""
      },
      {
        "date": "8月5日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材\n3.扫地",
        "mood": ""
      },
      {
        "date": "8月6日",
        "inspiration": "",
        "harvest": "1.实拍图生图步骤，尽量和 AI 一个系列一个系列的做，而不是一次性做几种风格\n2.写了就发的网站作图很方便，但是容易被系统判为 AI 创作，暂时先不用。",
        "task": "",
        "mood": ""
      },
      {
        "date": "8月7日",
        "inspiration": "",
        "harvest": "",
        "task": "找之前的排卵监测报告，看内膜长的情况\n看不二的个人网站，学习一下\n把这台 Mac 的数据都迁移到新 Mac，以后用新 Mac",
        "mood": ""
      },
      {
        "date": "8月10日",
        "inspiration": "",
        "harvest": "",
        "task": "晚上给杜爽爽视频问国庆要不要去马来西亚\n吃一盒酸奶+苹果桃子",
        "mood": ""
      },
      {
        "date": "8月12日",
        "inspiration": "",
        "harvest": "",
        "task": "缴7月社保",
        "mood": ""
      },
      {
        "date": "8月14日",
        "inspiration": "",
        "harvest": "",
        "task": "不做好物博主，看看是阿佳呀、水北山南的账号",
        "mood": ""
      },
      {
        "date": "8月20日",
        "inspiration": "",
        "harvest": "",
        "task": "用湿纸巾擦一下几个白色桌面",
        "mood": ""
      },
      {
        "date": "8月21日",
        "inspiration": "",
        "harvest": "",
        "task": "1.用湿纸巾擦一下几个白色桌面\n2.拖地\n3.看赵晗一个月流量情况\n4.重新调整几张电话卡\n5.等三个账号稳步运行后，用 AI 做一个自媒体工作台",
        "mood": ""
      },
      {
        "date": "8月24日",
        "inspiration": "",
        "harvest": "",
        "task": "1.盘点现有的好物，做分类，后面就可以根据现有产品做好物选题",
        "mood": ""
      }
    ],
    "last_updated": "6月24日",
    "today_updated": false
  },
  "finance": {
    "year_income": "¥595,774",
    "year_expense": "¥236,821",
    "monthly_data": [
      {
        "month": "2026年1月",
        "income": 91873.0,
        "expense": 29618.52
      },
      {
        "month": "2026年2月",
        "income": 39100.0,
        "expense": 46365.75
      },
      {
        "month": "2026年3月",
        "income": 37290.86,
        "expense": 40501.47
      },
      {
        "month": "2026年4月",
        "income": 39337.92,
        "expense": 40147.7
      },
      {
        "month": "2026年5月",
        "income": 276369.07,
        "expense": 29135.81
      },
      {
        "month": "2026年6月",
        "income": 33091.87,
        "expense": 27747.77
      }
    ],
    "yesterday_expense": "¥63.37",
    "last_updated": "2026-08-25",
    "last_month_expense": "¥23,304.58",
    "last_month_income": "¥34,711.87",
    "month_expense_to_yesterday": "¥19243.73",
    "income_annual": 24973,
    "income_ytd": 24973.0,
    "current_month_expense": "¥31110.13"
  },
  "reading": {
    "challenge_days": 170,
    "challenge_target": 365,
    "rolling_day": 170,
    "total_days": 1129,
    "weekly_read_time": 144,
    "yesterday_read_time": 70,
    "total_read_hours": 461,
    "total_read_books": 151,
    "currently_reading": [
      {
        "title": "诊疗椅上的谎言",
        "author": "[美]欧文·亚隆",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-25",
        "created": "2026-08-25"
      },
      {
        "title": "荷马史诗《伊利亚特》（罗念生全集·第六卷）",
        "author": "[古希腊]荷马",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-17",
        "created": "2026-08-17"
      },
      {
        "title": "动机心理学",
        "author": "[美]爱德华·伯克利  [美]梅利莎·伯克利",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-06",
        "created": "2026-08-06"
      },
      {
        "title": "我怎么这么会当妈",
        "author": "格十三",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-01",
        "created": "2026-08-01"
      },
      {
        "title": "他者中的华人：中国近现代移民史",
        "author": "孔飞力",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-07-31",
        "created": "2026-07-31"
      }
    ],
    "medals": [
      {
        "id": "M7-0-200",
        "type": 7,
        "subtype": 0,
        "level": 200,
        "ctime": 1783829092,
        "atime": 1783839061,
        "rank": 644409,
        "users": 656379,
        "hint": "想法发布 200 条",
        "renderItem": "07 / 12",
        "name": "想法发布",
        "index": 0,
        "availableCond": "累积达到200条",
        "tip": "再发表 0 条想法可得",
        "title": "想法发布",
        "rankText": "第644409位获得此勋章的书友",
        "displayText": "想法发布 200 条"
      },
      {
        "id": "M1-0-90",
        "type": 1,
        "subtype": 0,
        "level": 90,
        "ctime": 1778297612,
        "atime": 1778297636,
        "rank": 1894417,
        "users": 1941052,
        "hint": "连续阅读 90 天",
        "renderItem": "05 / 09",
        "name": "连续阅读",
        "index": 1,
        "availableCond": "累积达到90天",
        "tip": "再连续阅读 81 天可得",
        "title": "连续阅读",
        "rankText": "第1894417位获得此勋章的书友",
        "displayText": "连续阅读 90 天"
      },
      {
        "id": "M12-2-3-I-0-0-0",
        "type": 12,
        "subtype": 2,
        "level": 0,
        "ctime": 1776906259,
        "atime": 1776906259,
        "rank": 102178,
        "users": 472590,
        "hint": "你与华夏的文字格外投缘",
        "renderItem": "04 / 23",
        "name": "世界读书日",
        "index": 2,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "世界读书日",
        "rankText": "第102178位获得此勋章的书友",
        "displayText": "山水行吟客",
        "styleType": 1,
        "styleTitle": "山水行吟客",
        "styleDesc": "你与华夏的文字格外投缘"
      },
      {
        "id": "M3-0-1000",
        "type": 3,
        "subtype": 0,
        "level": 1000,
        "ctime": 1776347296,
        "atime": 1776347477,
        "rank": 1755752,
        "users": 1815102,
        "hint": "阅读 1000 天",
        "renderItem": "04 / 16",
        "name": "阅读天数",
        "index": 3,
        "availableCond": "累积达到1000天",
        "tip": "再阅读 0 天可得",
        "title": "阅读天数",
        "rankText": "第1755752位获得此勋章的书友",
        "displayText": "阅读 1000 天"
      },
      {
        "id": "M15-2-0",
        "type": 15,
        "subtype": 2,
        "level": 0,
        "ctime": 1774972748,
        "atime": 1774972748,
        "rank": 697853,
        "users": 809001,
        "hint": "21天阅读挑战",
        "renderItem": "03 / 31",
        "name": "21天阅读挑战",
        "index": 4,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "21天阅读挑战",
        "rankText": "成功挑战2次 · 第697853位获得此勋章的书友",
        "displayText": "21天阅读挑战"
      }
    ],
    "last_updated": "2026-08-25",
    "total_finished_books": 66,
    "weekly_data": {
      "weekly_read_time": 144,
      "yesterday_read_time": 70,
      "source": "周数据"
    },
    "total_data": {
      "total_read_hours": 461,
      "total_read_books": 151,
      "total_finished_books": 66,
      "source": "总数据"
    }
  },
  "published_notes": {
    "total": 153,
    "last_updated": "2026-08-25",
    "month_count": 42
  },
  "exercise": {
    "month": "2026年7月",
    "month_key": "2026-07",
    "month_label": "7月",
    "week_header": [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "日"
    ],
    "exercise_blocks": [
      {
        "emoji": "🧘",
        "name": "体态矫正",
        "color": "#FF6B9D",
        "videos": [
          {
            "title": "【欧阳春晓】15min告别肩背肥厚",
            "bvid": "BV1Qv411t7EN",
            "duration": "15:00"
          },
          {
            "title": "MIZI · 改善圆肩驼背｜跟练版",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "12:00"
          },
          {
            "title": "骨盆前倾矫正｜每天10分钟",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          }
        ]
      },
      {
        "emoji": "🔥",
        "name": "燃脂训练",
        "color": "#FF9F43",
        "videos": [
          {
            "title": "帕梅拉 · 15min全身燃脂｜暴汗",
            "bvid": "BV1qK4y1t7fP",
            "duration": "15:00"
          },
          {
            "title": "Eleni Fit · 30min站立燃脂｜新手友好",
            "bvid": "BV1GJ411x7h7",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 14天瘦大腿内侧｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "28:00"
          }
        ]
      },
      {
        "emoji": "💪",
        "name": "力量塑形",
        "color": "#4ECDC4",
        "videos": [
          {
            "title": "蜜桃臀养成 · 31min跟练版",
            "bvid": "BV1GJ411x7h7",
            "duration": "31:00"
          },
          {
            "title": "Barre · 30min肩背塑形",
            "bvid": "BV1qK4y1t7fP",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 2周瘦手臂｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "21:00"
          }
        ]
      },
      {
        "emoji": "🫁",
        "name": "拉伸放松",
        "color": "#A29BFE",
        "videos": [
          {
            "title": "全身拉伸放松 · 10min",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          },
          {
            "title": "腿部拉伸 · 睡前10min",
            "bvid": "BV1qK4y1t7fP",
            "duration": "10:00"
          },
          {
            "title": "阴瑜伽 · 放松30min",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "30:00"
          }
        ]
      }
    ]
  },
  "oneCompany": {
    "total_revenue": "¥279.6",
    "total_orders": 14,
    "products": [
      {
        "name": "新手妈妈孕期必备知识库｜0-40周全阶段｜第一次怀孕+焦虑型妈妈",
        "price": "¥39.9"
      },
      {
        "name": "第一次怀孕安心决策系统｜0-40周遇到问题不慌知道下一步怎么办",
        "price": "¥39.9"
      },
      {
        "name": "准妈妈0-40周孕期安心知识库｜从怀孕到分娩的安心决策工具",
        "price": "¥39.9"
      },
      {
        "name": "流产后身心恢复指南｜身心重建+饮食调理+备孕指导+伴侣沟通",
        "price": "¥9.9"
      }
    ],
    "total_published_notes": 153,
    "monthly_revenue": [],
    "weekly_revenue": [
      {
        "label": "7/20",
        "revenue": 0
      },
      {
        "label": "7/27",
        "revenue": 6.9
      },
      {
        "label": "8/3",
        "revenue": 79.8
      },
      {
        "label": "8/10",
        "revenue": 0
      },
      {
        "label": "8/17",
        "revenue": 0
      },
      {
        "label": "8/24",
        "revenue": 0
      }
    ],
    "last_updated": "2026-08-25"
  },
  "hotTopics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 这期「乳房自救指南」，夯爆了！| Vol.176",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "4天前"
      },
      {
        "title": "🎙 嗨咻 | 102.和柱子哥阿娇聊天｜横竖都是死，我为什么不做我？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "6天前"
      },
      {
        "title": "🎙 头回当妈 | 101.经典回顾｜中西方带娃理念禁忌大比拼",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "2周前"
      },
      {
        "title": "🎙 畅所育言 | 113入园大作战：准备好书包，也准备好第一次告别",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "4天前"
      },
      {
        "title": "🎙 【Alison Yu心理】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-08-25",
    "ai_news": [
      {
        "title": "Apple 推出搭载 M5 Max 与 M5 Ultra 的全新 Mac Studio",
        "url": "https://aihot.virxact.com/items/cmt8qee503kvnro73qp7543yv",
        "published": "Tue, 25 Aug 2026 13:00:23 GMT",
        "source": "Apple：Newsroom（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "Apple 发布 M6 与 M5 Ultra，性能与 AI 算力大幅跃升",
        "url": "https://aihot.virxact.com/items/cmt8qee503kvpro73kzthenuu",
        "published": "Tue, 25 Aug 2026 12:58:13 GMT",
        "source": "Apple：Newsroom（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "MetaRoCE：为 AI 规模以太网打造的全新 RDMA 传输协议",
        "url": "https://aihot.virxact.com/items/cmt7nq1d02bs1ro7373u88po4",
        "published": "Mon, 24 Aug 2026 18:02:29 GMT",
        "source": "Meta Engineering Blog（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "NVIDIA Vera Rubin NVL72 树立 AI 智能体效率新标准：每瓦特工作量提升至 30 倍",
        "url": "https://aihot.virxact.com/items/cmt7e0g7y232wro738qg82x67",
        "published": "Mon, 24 Aug 2026 15:00:19 GMT",
        "source": "NVIDIA Blog（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 正为一切构建 AI 智能体，但用户会愿意交出控制权吗？",
        "url": "https://aihot.virxact.com/items/cmt7e3m7h234gro73wwwhymb0",
        "published": "Mon, 24 Aug 2026 15:00:00 GMT",
        "source": "TechCrunch：AI（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "GPT-5.6 登陆 Kiro，为开发者提升性价比",
        "url": "https://aihot.virxact.com/items/cmt7nzq6i2c27ro73tqxagz44",
        "published": "Mon, 24 Aug 2026 12:00:00 GMT",
        "source": "OpenAI：官网动态（RSS · 排除企业/客户案例）",
        "time_ago": "昨天"
      },
      {
        "title": "单个污染页面即可影响LLM推荐：FORGE基准揭示检索增强推荐系统的脆弱性",
        "url": "https://aihot.virxact.com/items/cmt8bo2db30oaro735zu90tig",
        "published": "Mon, 24 Aug 2026 00:00:00 GMT",
        "source": "HuggingFace Daily Papers（社区热门论文）",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 首席全球事务官勒汉恩：公众、企业要为 AI 网络攻击做好防御准备",
        "url": "https://aihot.virxact.com/items/cmt5wf8hm0shgro737h9vww1k",
        "published": "Sun, 23 Aug 2026 14:13:31 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "2天前"
      },
      {
        "title": "德克萨斯州一名学生如何揭发了一起恶意AI黑客攻击企图",
        "url": "https://aihot.virxact.com/items/cmt53k3d704o3ro73oylvm5ln",
        "published": "Sun, 23 Aug 2026 00:53:34 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "2天前"
      },
      {
        "title": "AI 基础设施的牛鞭效应：从 GPU 到存储的连锁瓶颈",
        "url": "https://aihot.virxact.com/items/cmt7cxb9t22baro73x9ys4bnr",
        "published": "Sun, 23 Aug 2026 00:00:00 GMT",
        "source": "Tomer Tunguz 博客（VC 分析）",
        "time_ago": "2天前"
      }
    ],
    "one_company_news": [
      {
        "title": "330天后，安世中国管理团队重磅发布，看他们带来了什么？",
        "url": "https://www.tmtpost.com/8115056.html",
        "published": "Tue, 25 Aug 2026 19:29:39 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "苹果 Mac mini M6 发布：两年涨 2500 块，AI 税反噬「龙虾神机」",
        "url": "http://www.geekpark.net/news/369354",
        "published": "Tue, 25 Aug 2026 22:46:38 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "27.98 万元起，泰钽 700 正式上市，越野 NOA 开上挂壁公路",
        "url": "https://www.ifanr.com/1676715?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Tue, 25 Aug 2026 14:13:09 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "last_sync": "2026-08-25 23:31",
  "expense_categories": {
    "items": [
      {
        "rank": 1,
        "category": "房贷",
        "emoji": "🏠",
        "amount": "¥7,927",
        "amount_raw": 7927.4,
        "percent": 100
      },
      {
        "rank": 2,
        "category": "房租",
        "emoji": "🏠",
        "amount": "¥4,530",
        "amount_raw": 4530.0,
        "percent": 57
      },
      {
        "rank": 3,
        "category": "赵晗支出",
        "emoji": "👤",
        "amount": "¥3,518",
        "amount_raw": 3518.07,
        "percent": 44
      },
      {
        "rank": 4,
        "category": "固定支出",
        "emoji": "🔒",
        "amount": "¥2,667",
        "amount_raw": 2667.27,
        "percent": 34
      },
      {
        "rank": 5,
        "category": "公交打车",
        "emoji": "📌",
        "amount": "¥1,266",
        "amount_raw": 1266.0700000000002,
        "percent": 16
      },
      {
        "rank": 6,
        "category": "零食奶茶",
        "emoji": "📌",
        "amount": "¥926",
        "amount_raw": 926.73,
        "percent": 12
      },
      {
        "rank": 7,
        "category": "一日三餐",
        "emoji": "🍽️",
        "amount": "¥884",
        "amount_raw": 884.7199999999999,
        "percent": 11
      }
    ],
    "month": "2026年7月",
    "last_updated": "2026-08-25"
  },
  "hot_topics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 这期「乳房自救指南」，夯爆了！| Vol.176",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "4天前"
      },
      {
        "title": "🎙 嗨咻 | 102.和柱子哥阿娇聊天｜横竖都是死，我为什么不做我？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "6天前"
      },
      {
        "title": "🎙 头回当妈 | 101.经典回顾｜中西方带娃理念禁忌大比拼",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "2周前"
      },
      {
        "title": "🎙 畅所育言 | 113入园大作战：准备好书包，也准备好第一次告别",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "4天前"
      },
      {
        "title": "🎙 【Alison Yu心理】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-08-25",
    "ai_news": [
      {
        "title": "Apple 推出搭载 M5 Max 与 M5 Ultra 的全新 Mac Studio",
        "url": "https://aihot.virxact.com/items/cmt8qee503kvnro73qp7543yv",
        "published": "Tue, 25 Aug 2026 13:00:23 GMT",
        "source": "Apple：Newsroom（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "Apple 发布 M6 与 M5 Ultra，性能与 AI 算力大幅跃升",
        "url": "https://aihot.virxact.com/items/cmt8qee503kvpro73kzthenuu",
        "published": "Tue, 25 Aug 2026 12:58:13 GMT",
        "source": "Apple：Newsroom（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "MetaRoCE：为 AI 规模以太网打造的全新 RDMA 传输协议",
        "url": "https://aihot.virxact.com/items/cmt7nq1d02bs1ro7373u88po4",
        "published": "Mon, 24 Aug 2026 18:02:29 GMT",
        "source": "Meta Engineering Blog（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "NVIDIA Vera Rubin NVL72 树立 AI 智能体效率新标准：每瓦特工作量提升至 30 倍",
        "url": "https://aihot.virxact.com/items/cmt7e0g7y232wro738qg82x67",
        "published": "Mon, 24 Aug 2026 15:00:19 GMT",
        "source": "NVIDIA Blog（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 正为一切构建 AI 智能体，但用户会愿意交出控制权吗？",
        "url": "https://aihot.virxact.com/items/cmt7e3m7h234gro73wwwhymb0",
        "published": "Mon, 24 Aug 2026 15:00:00 GMT",
        "source": "TechCrunch：AI（RSS）",
        "time_ago": "昨天"
      },
      {
        "title": "GPT-5.6 登陆 Kiro，为开发者提升性价比",
        "url": "https://aihot.virxact.com/items/cmt7nzq6i2c27ro73tqxagz44",
        "published": "Mon, 24 Aug 2026 12:00:00 GMT",
        "source": "OpenAI：官网动态（RSS · 排除企业/客户案例）",
        "time_ago": "昨天"
      },
      {
        "title": "单个污染页面即可影响LLM推荐：FORGE基准揭示检索增强推荐系统的脆弱性",
        "url": "https://aihot.virxact.com/items/cmt8bo2db30oaro735zu90tig",
        "published": "Mon, 24 Aug 2026 00:00:00 GMT",
        "source": "HuggingFace Daily Papers（社区热门论文）",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 首席全球事务官勒汉恩：公众、企业要为 AI 网络攻击做好防御准备",
        "url": "https://aihot.virxact.com/items/cmt5wf8hm0shgro737h9vww1k",
        "published": "Sun, 23 Aug 2026 14:13:31 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "2天前"
      },
      {
        "title": "德克萨斯州一名学生如何揭发了一起恶意AI黑客攻击企图",
        "url": "https://aihot.virxact.com/items/cmt53k3d704o3ro73oylvm5ln",
        "published": "Sun, 23 Aug 2026 00:53:34 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "2天前"
      },
      {
        "title": "AI 基础设施的牛鞭效应：从 GPU 到存储的连锁瓶颈",
        "url": "https://aihot.virxact.com/items/cmt7cxb9t22baro73x9ys4bnr",
        "published": "Sun, 23 Aug 2026 00:00:00 GMT",
        "source": "Tomer Tunguz 博客（VC 分析）",
        "time_ago": "2天前"
      }
    ],
    "one_company_news": [
      {
        "title": "330天后，安世中国管理团队重磅发布，看他们带来了什么？",
        "url": "https://www.tmtpost.com/8115056.html",
        "published": "Tue, 25 Aug 2026 19:29:39 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "苹果 Mac mini M6 发布：两年涨 2500 块，AI 税反噬「龙虾神机」",
        "url": "http://www.geekpark.net/news/369354",
        "published": "Tue, 25 Aug 2026 22:46:38 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "27.98 万元起，泰钽 700 正式上市，越野 NOA 开上挂壁公路",
        "url": "https://www.ifanr.com/1676715?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Tue, 25 Aug 2026 14:13:09 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "weather": {
    "cities": {
      "beijing": {
        "name": "北京 · 顺义",
        "temp": 23.7,
        "weather_code": 51,
        "desc": "🌦 毛毛雨",
        "min": 23.6,
        "max": 29.8
      },
      "wuhan": {
        "name": "武汉 · 洪山",
        "temp": 30.4,
        "weather_code": 0,
        "desc": "☀️ 晴",
        "min": 28.4,
        "max": 35.5
      }
    },
    "last_updated": "2026-08-25 23:30"
  },
  "inspirations_done": {
    "task:挂周一的号-北京妇产医院": true,
    "task:买山药粉": true,
    "task:做鸡肉干": true,
    "task:确认一下 AI 资讯数据来源和已发布笔记数据是否正确": true,
    "task:和杜爽爽视频": true,
    "task:调研一下爆款笔记，关键词：生育、成为妈妈、怀孕": true,
    "task:把我的人生系统这个网站做一下优化迭代": true,
    "task:上架新产品，做 3 个 sku": true,
    "task:扫地": true,
    "task:看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材": true,
    "task:缴7月社保": true,
    "task:不做好物博主，看看是阿佳呀、水北山南的账号": true,
    "task:用湿纸巾擦一下几个白色桌面": true,
    "task:拖地": true,
    "task:看赵晗一个月流量情况": true,
    "task:重新调整几张电话卡": true
  }
};
