// Auto-generated by feishu_sync.py
// Last updated: 2026-07-30 18:30
const DASHBOARD_DATA = {
  "tasks": {
    "date": "7月30日",
    "items": [
      {
        "text": "1.润色&定稿：写10篇笔记",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "2.研究微信小程序部署，参考分享狗狗喂养指南的那个博主的分享",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "3.用Obsidian和ChatGPT live搭建英语学习语料库，再用workbuddy搭建一个英语学习网站",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "4.用 workbuddy 把电脑上的 skill 处理一下",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "5.安装一下发现的几个不错的 skill",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "6.研究一下 Claude 账号，可以买个 poe 会员，这样就可以用各种模型，看看不同模型的效果了",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_text": "1.润色&定稿：写10篇笔记\n2.研究微信小程序部署，参考分享狗狗喂养指南的那个博主的分享\n3.用Obsidian和ChatGPT live搭建英语学习语料库，再用workbuddy搭建一个英语学习网站\n4.用 workbuddy 把电脑上的 skill 处理一下\n5.安装一下发现的几个不错的 skill \n6.研究一下 Claude 账号，可以买个 poe 会员，这样就可以用各种模型，看看不同模型的效果了",
    "tasks": [
      {
        "text": "搞清楚GitHub的界面和使用方法",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "研究一下flova",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "安装workbuddy的教程，把ima 知识库打通做小程序",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "润色&定稿：6篇小红书笔记",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "下载小红书数据，让 AI分析数据做下一步运营方向",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "参考胡楚靓的个人工作台做法，做孕期工作台，做完分享在账号上看看反馈",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "把已经装的skills整理到文档做备份",
        "done": false,
        "cancelled": false,
        "priority": "mid"
      },
      {
        "text": "继续完善人生系统工作台",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_tasks_text": "1.搞清楚GitHub的界面和使用方法\n2.研究一下flova\n3.安装workbuddy的教程，把ima 知识库打通做小程序\n4.润色&定稿：6篇小红书笔记\n5.下载小红书数据，让 AI分析数据做下一步运营方向\n6.参考胡楚靓的个人工作台做法，做孕期工作台，做完分享在账号上看看反馈\n7.把已经装的skills整理到文档做备份\n8.继续完善人生系统工作台"
  },
  "memos": {
    "items": [
      {
        "date": "7月29日",
        "text": "流产后身心恢复指南，卖的更好，是不是可以继续开发类似的产品",
        "id": "memo_37_1"
      },
      {
        "date": "7月29日",
        "text": "孕期记录工作台：用 Workbuddy 搭孕期记录工具，先分享，如果很多人不会用可以打包成 skill 出售",
        "id": "memo_37_0"
      },
      {
        "date": "7月28日",
        "text": "学习红十字会急救培训课程",
        "id": "memo_36_9"
      },
      {
        "date": "7月28日",
        "text": "看3个AI分享大会",
        "id": "memo_36_8"
      },
      {
        "date": "7月28日",
        "text": "实践张咋啦分享的各类AI产品",
        "id": "memo_36_7"
      },
      {
        "date": "7月28日",
        "text": "孕期知识库，后续可考虑逐步补充待产包、准爸爸参与手册、怀孕书单读书笔记、孕吐缓解指南（正好可以保持持续更新的卖点）",
        "id": "memo_36_6"
      },
      {
        "date": "7月28日",
        "text": "参考松月的养生知识库做一个孕期食谱（不一定卖主要是为了操作一遍）",
        "id": "memo_36_5"
      },
      {
        "date": "7月28日",
        "text": "孕期报告解读助手的工具，后续可以研究一下怎么变成产品售卖——http://localhost:8501/",
        "id": "memo_36_4"
      },
      {
        "date": "7月28日",
        "text": "研究并搞懂小程序开发的流程和各种概念",
        "id": "memo_36_3"
      },
      {
        "date": "7月28日",
        "text": "自己制作一套提示词/skills，这个要实操一下",
        "id": "memo_36_2"
      }
    ],
    "total": 10
  },
  "inspirations": {
    "items": [
      {
        "date": "6月24日",
        "inspiration": "",
        "harvest": "",
        "task": "",
        "mood": "test full range"
      },
      {
        "date": "7月27日",
        "inspiration": "",
        "harvest": "让AI直接读取我的飞书选题表格，做好排期后，让它一键写笔记，不用我再一个个选题发给它们了",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月28日",
        "inspiration": "",
        "harvest": "1.学会了借助skill优化网站\n2.发现了飞书字段有一个【字段捷径中心】，可以把现有字段转换为其他想要的字段形式，比如日期变成年月\n3.把做人生系统个人网站的经验封装成了life-dashboard-builder Skill",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月30日",
        "inspiration": "",
        "harvest": "",
        "task": "1.挂周一的号-北京妇产医院\n2.买山药粉\n3.做鸡肉干",
        "mood": ""
      }
    ],
    "last_updated": "6月24日",
    "today_updated": true
  },
  "finance": {
    "year_income": "¥551,774",
    "year_expense": "¥212,782",
    "monthly_data": [
      {
        "month": "2026年1月",
        "income": 91873.0,
        "expense": 32490.61
      },
      {
        "month": "2026年2月",
        "income": 39100.0,
        "expense": 40569.82
      },
      {
        "month": "2026年3月",
        "income": 37290.86,
        "expense": 40501.47
      },
      {
        "month": "2026年4月",
        "income": 39337.92,
        "expense": 40216.34
      },
      {
        "month": "2026年5月",
        "income": 276369.07,
        "expense": 31256.85
      },
      {
        "month": "2026年6月",
        "income": 33091.87,
        "expense": 27747.77
      }
    ],
    "yesterday_expense": "¥12.00",
    "last_updated": "2026-07-30",
    "last_month_expense": "¥27,747.77",
    "last_month_income": "¥33,091.87"
  },
  "reading": {
    "challenge_days": 1102,
    "challenge_target": 365,
    "rolling_day": 144,
    "total_days": 0,
    "weekly_read_time": 59,
    "yesterday_read_time": 24,
    "total_read_hours": 452,
    "total_read_books": 148,
    "currently_reading": [
      {
        "title": "他者中的华人：中国近现代移民史",
        "author": "孔飞力",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-07-30",
        "created": "2026-07-30"
      },
      {
        "title": "你的夏天还好吗？",
        "author": "金爱烂",
        "status": "已读",
        "progress": 50,
        "last_read": "2026-07-30",
        "created": "2026-07-30"
      },
      {
        "title": "孽子",
        "author": "白先勇",
        "status": "已读",
        "progress": 50,
        "last_read": "2026-07-28",
        "created": "2026-07-28"
      },
      {
        "title": "孩子王（轻经典）",
        "author": "阿城",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-07-27",
        "created": "2026-07-27"
      },
      {
        "title": "金钱心理学：财富、人性和幸福的永恒真相",
        "author": "摩根·豪泽尔",
        "status": "已读",
        "progress": 50,
        "last_read": "2026-07-27",
        "created": "2026-07-27"
      }
    ],
    "medals": [
      {
        "id": "M7-0-200",
        "type": 7,
        "subtype": 0,
        "level": 200,
        "ctime": 1783829092,
        "atime": 1783839061,
        "rank": 644409,
        "users": 649078,
        "hint": "想法发布 200 条",
        "renderItem": "07 / 12",
        "name": "想法发布",
        "index": 0,
        "availableCond": "累积达到200条",
        "tip": "再发表 0 条想法可得",
        "title": "想法发布",
        "rankText": "第644409位获得此勋章的书友",
        "displayText": "想法发布 200 条"
      },
      {
        "id": "M1-0-90",
        "type": 1,
        "subtype": 0,
        "level": 90,
        "ctime": 1778297612,
        "atime": 1778297636,
        "rank": 1894417,
        "users": 1930003,
        "hint": "连续阅读 90 天",
        "renderItem": "05 / 09",
        "name": "连续阅读",
        "index": 1,
        "availableCond": "累积达到90天",
        "tip": "再连续阅读 71 天可得",
        "title": "连续阅读",
        "rankText": "第1894417位获得此勋章的书友",
        "displayText": "连续阅读 90 天"
      },
      {
        "id": "M12-2-3-I-0-0-0",
        "type": 12,
        "subtype": 2,
        "level": 0,
        "ctime": 1776906259,
        "atime": 1776906259,
        "rank": 102178,
        "users": 472590,
        "hint": "你与华夏的文字格外投缘",
        "renderItem": "04 / 23",
        "name": "世界读书日",
        "index": 2,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "世界读书日",
        "rankText": "第102178位获得此勋章的书友",
        "displayText": "山水行吟客",
        "styleType": 1,
        "styleTitle": "山水行吟客",
        "styleDesc": "你与华夏的文字格外投缘"
      },
      {
        "id": "M3-0-1000",
        "type": 3,
        "subtype": 0,
        "level": 1000,
        "ctime": 1776347296,
        "atime": 1776347477,
        "rank": 1755752,
        "users": 1803316,
        "hint": "阅读 1000 天",
        "renderItem": "04 / 16",
        "name": "阅读天数",
        "index": 3,
        "availableCond": "累积达到1000天",
        "tip": "再阅读 0 天可得",
        "title": "阅读天数",
        "rankText": "第1755752位获得此勋章的书友",
        "displayText": "阅读 1000 天"
      },
      {
        "id": "M15-2-0",
        "type": 15,
        "subtype": 2,
        "level": 0,
        "ctime": 1774972748,
        "atime": 1774972748,
        "rank": 697853,
        "users": 790844,
        "hint": "21天阅读挑战",
        "renderItem": "03 / 31",
        "name": "21天阅读挑战",
        "index": 4,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "21天阅读挑战",
        "rankText": "成功挑战2次 · 第697853位获得此勋章的书友",
        "displayText": "21天阅读挑战"
      }
    ],
    "last_updated": "2026-07-30",
    "total_finished_books": 64,
    "weekly_data": {
      "weekly_read_time": 59,
      "yesterday_read_time": 24,
      "source": "周数据"
    },
    "total_data": {
      "total_read_hours": 452,
      "total_read_books": 148,
      "total_finished_books": 64,
      "source": "总数据"
    }
  },
  "published_notes": {
    "total": 110,
    "last_updated": "2026-07-30"
  },
  "exercise": {
    "month": "2026年7月",
    "month_key": "2026-07",
    "month_label": "7月",
    "week_header": [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "日"
    ],
    "exercise_blocks": [
      {
        "emoji": "🧘",
        "name": "体态矫正",
        "color": "#FF6B9D",
        "videos": [
          {
            "title": "【欧阳春晓】15min告别肩背肥厚",
            "bvid": "BV1Qv411t7EN",
            "duration": "15:00"
          },
          {
            "title": "MIZI · 改善圆肩驼背｜跟练版",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "12:00"
          },
          {
            "title": "骨盆前倾矫正｜每天10分钟",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          }
        ]
      },
      {
        "emoji": "🔥",
        "name": "燃脂训练",
        "color": "#FF9F43",
        "videos": [
          {
            "title": "帕梅拉 · 15min全身燃脂｜暴汗",
            "bvid": "BV1qK4y1t7fP",
            "duration": "15:00"
          },
          {
            "title": "Eleni Fit · 30min站立燃脂｜新手友好",
            "bvid": "BV1GJ411x7h7",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 14天瘦大腿内侧｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "28:00"
          }
        ]
      },
      {
        "emoji": "💪",
        "name": "力量塑形",
        "color": "#4ECDC4",
        "videos": [
          {
            "title": "蜜桃臀养成 · 31min跟练版",
            "bvid": "BV1GJ411x7h7",
            "duration": "31:00"
          },
          {
            "title": "Barre · 30min肩背塑形",
            "bvid": "BV1qK4y1t7fP",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 2周瘦手臂｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "21:00"
          }
        ]
      },
      {
        "emoji": "🫁",
        "name": "拉伸放松",
        "color": "#A29BFE",
        "videos": [
          {
            "title": "全身拉伸放松 · 10min",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          },
          {
            "title": "腿部拉伸 · 睡前10min",
            "bvid": "BV1qK4y1t7fP",
            "duration": "10:00"
          },
          {
            "title": "阴瑜伽 · 放松30min",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "30:00"
          }
        ]
      }
    ]
  },
  "oneCompany": {
    "total_revenue": "¥179",
    "total_orders": 9,
    "products": [
      {
        "name": "孕期安心知识库",
        "price": "¥39.9"
      },
      {
        "name": "产后恢复指南",
        "price": "¥9.9"
      }
    ],
    "total_published_notes": 110,
    "monthly_revenue": []
  },
  "hotTopics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 怎么无痛的出血，反而更要命啊？！｜有点小事60",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      },
      {
        "title": "🎙 嗨咻 | 100. 为什么越想表现自己，越容易在社交中露怯？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      },
      {
        "title": "🎙 头回当妈 | 100. 特别节目｜头回当妈的101问 第一弹",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      },
      {
        "title": "🎙 畅所育言 | 110把感激误认为爱情，把健身练成疲劳，把AI当成答案｜最近想分享的6期播客",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 【Alison Yu心理】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-07-30",
    "ai_news": [
      {
        "title": "Token Saver：用本地混合 RAG 将 Claude PDF token 消耗削减 92%-99% 的开源 MCP 扩展",
        "url": "https://aihot.virxact.com/items/cms782fxi02w4ro2evmcwz6uj",
        "published": "Thu, 30 Jul 2026 07:43:29 GMT",
        "source": "MarkTechPost（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "OpenAI 总裁布罗克曼承认新版 ChatGPT 桌面应用&quot;有点乱&quot;，目标年底实现&quot;零标签&quot;",
        "url": "https://aihot.virxact.com/items/cms6xky2402xgrouqgudkfgsg",
        "published": "Thu, 30 Jul 2026 02:49:47 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "腾讯混元Hyra破解50年数学难题",
        "url": "https://aihot.virxact.com/items/cms6xa31u02nlrouq0wkhylfp",
        "published": "Thu, 30 Jul 2026 02:33:16 GMT",
        "source": "X：腾讯混元 (@TencentHunyuan)",
        "time_ago": "今天"
      },
      {
        "title": "揭秘 AI 智能体入侵 Hugging Face 全过程：4 天半执行 17600 次操作",
        "url": "https://aihot.virxact.com/items/cms6r5fog0btjrohz9heu2c6f",
        "published": "Wed, 29 Jul 2026 23:29:34 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "Replit Design 发布：AI 赋能设计愿景",
        "url": "https://aihot.virxact.com/items/cms6kdopf05tbrohzoim2kpeg",
        "published": "Wed, 29 Jul 2026 20:45:42 GMT",
        "source": "X：Replit (@Replit)",
        "time_ago": "今天"
      },
      {
        "title": "Claude Opus 5 在模拟售货机任务中展现欺骗与背叛，创下新纪录",
        "url": "https://aihot.virxact.com/items/cms6g4nn502errohzoxo9al2o",
        "published": "Wed, 29 Jul 2026 18:45:27 GMT",
        "source": "TechCrunch：AI（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "Miles 在 Blackwell 架构上实现端到端 MXFP8 与逐 token NVFP4 强化学习方案",
        "url": "https://aihot.virxact.com/items/cms6drkj8001crohzuxf7kfy7",
        "published": "Wed, 29 Jul 2026 17:50:30 GMT",
        "source": "LMSYS：Blog（Chatbot Arena 团队）",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 为学术研究者免费提供前沿模型",
        "url": "https://aihot.virxact.com/items/cms6cw5ha02sgrotzfmlr8p11",
        "published": "Wed, 29 Jul 2026 17:22:02 GMT",
        "source": "X：Sherwin Wu（@sherwinwu）",
        "time_ago": "昨天"
      },
      {
        "title": "Perplexity 开源智能体检测层 Numbat",
        "url": "https://aihot.virxact.com/items/cms6czboh031krotzmczxbw2v",
        "published": "Wed, 29 Jul 2026 17:01:42 GMT",
        "source": "X：Perplexity (@perplexity_ai)",
        "time_ago": "昨天"
      },
      {
        "title": "开源引擎可在任何 M 系列 Mac 上以 2 GB 内存运行 Gemma 4 26B",
        "url": "https://aihot.virxact.com/items/cms6arrc700rbrotzo1wseql3",
        "published": "Wed, 29 Jul 2026 16:09:22 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "昨天"
      }
    ],
    "one_company_news": [
      {
        "title": "上半年美股复盘：存储芯片半导体，K线虐我如蝼蚁",
        "url": "https://www.ximalaya.com/sound/1003587637",
        "published": "Wed, 29 Jul 2026 23:30:00 GMT",
        "author": "",
        "source": "亏钱指南",
        "time_ago": "今天",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6615cd1e5b4c7f0012fd9c7a"
      },
      {
        "title": "00后摆脱搞钱羞耻：做明星应援扇月入过万，摆摊穿戴甲日入五百",
        "url": "https://www.ximalaya.com/sound/1002371330",
        "published": "Wed, 22 Jul 2026 23:30:00 GMT",
        "author": "",
        "source": "亏钱指南",
        "time_ago": "1周前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6615cd1e5b4c7f0012fd9c7a"
      },
      {
        "title": "vol.53 对谈易立竞：折腾vs独处 极致对照组的两种活法答案",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a66487e6356eb2d9be8ca46?utm_source=rss",
        "published": "Mon, 27 Jul 2026 00:00:00 GMT",
        "author": "",
        "source": "天真不天真",
        "time_ago": "3天前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6473f1b85b4c7f0012fd9bf8"
      },
      {
        "title": "vol.52 对谈王安宇：十年可以让一个人发生多少变化",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a4a7af02e335a35a80e7c18?utm_source=rss",
        "published": "Mon, 06 Jul 2026 00:00:00 GMT",
        "author": "",
        "source": "天真不天真",
        "time_ago": "3周前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6473f1b85b4c7f0012fd9bf8"
      },
      {
        "title": "【截胡不截财】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/65e9c5e9d5e8d90013f65ab8",
        "source": "截胡不截财",
        "time_ago": "📱 点击在小宇宙App收听"
      },
      {
        "title": "269. 卷规模 VS 卷创作：真人短剧的两种生存模式",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a4f777d1e32575f5eb3cbc1?utm_source=rss",
        "published": "Thu, 09 Jul 2026 10:32:06 GMT",
        "author": "",
        "source": "乱翻书",
        "time_ago": "3周前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6416be6e5b4c7f0012fd9b86"
      },
      {
        "title": "268.AI时代，个人工作台会重新回到手机吗？",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a3bdd319d2f5743683d4841?utm_source=rss",
        "published": "Wed, 24 Jun 2026 13:49:54 GMT",
        "author": "",
        "source": "乱翻书",
        "time_ago": "1月前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6416be6e5b4c7f0012fd9b86"
      }
    ]
  },
  "last_sync": "2026-07-30 18:30",
  "expense_categories": {
    "items": [
      {
        "rank": 1,
        "category": "房贷",
        "emoji": "🏠",
        "amount": "¥7,927",
        "amount_raw": 7927.4,
        "percent": 100
      },
      {
        "rank": 2,
        "category": "赵晗支出",
        "emoji": "👤",
        "amount": "¥5,693",
        "amount_raw": 5693.59,
        "percent": 72
      },
      {
        "rank": 3,
        "category": "房租",
        "emoji": "🏠",
        "amount": "¥3,800",
        "amount_raw": 3800.0,
        "percent": 48
      },
      {
        "rank": 4,
        "category": "武装大脑",
        "emoji": "📚",
        "amount": "¥3,349",
        "amount_raw": 3349.05,
        "percent": 42
      },
      {
        "rank": 5,
        "category": "固定支出",
        "emoji": "🔒",
        "amount": "¥2,667",
        "amount_raw": 2667.27,
        "percent": 34
      },
      {
        "rank": 6,
        "category": "买药看病",
        "emoji": "🏥",
        "amount": "¥2,147",
        "amount_raw": 2147.12,
        "percent": 27
      },
      {
        "rank": 7,
        "category": "一日三餐",
        "emoji": "🍽️",
        "amount": "¥1,168",
        "amount_raw": 1168.57,
        "percent": 15
      }
    ],
    "month": "2026年6月",
    "last_updated": "2026-07-30"
  },
  "hot_topics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 怎么无痛的出血，反而更要命啊？！｜有点小事60",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      },
      {
        "title": "🎙 嗨咻 | 100. 为什么越想表现自己，越容易在社交中露怯？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      },
      {
        "title": "🎙 头回当妈 | 100. 特别节目｜头回当妈的101问 第一弹",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "昨天"
      },
      {
        "title": "🎙 畅所育言 | 110把感激误认为爱情，把健身练成疲劳，把AI当成答案｜最近想分享的6期播客",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 【Alison Yu心理】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-07-30",
    "ai_news": [
      {
        "title": "Token Saver：用本地混合 RAG 将 Claude PDF token 消耗削减 92%-99% 的开源 MCP 扩展",
        "url": "https://aihot.virxact.com/items/cms782fxi02w4ro2evmcwz6uj",
        "published": "Thu, 30 Jul 2026 07:43:29 GMT",
        "source": "MarkTechPost（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "OpenAI 总裁布罗克曼承认新版 ChatGPT 桌面应用&quot;有点乱&quot;，目标年底实现&quot;零标签&quot;",
        "url": "https://aihot.virxact.com/items/cms6xky2402xgrouqgudkfgsg",
        "published": "Thu, 30 Jul 2026 02:49:47 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "腾讯混元Hyra破解50年数学难题",
        "url": "https://aihot.virxact.com/items/cms6xa31u02nlrouq0wkhylfp",
        "published": "Thu, 30 Jul 2026 02:33:16 GMT",
        "source": "X：腾讯混元 (@TencentHunyuan)",
        "time_ago": "今天"
      },
      {
        "title": "揭秘 AI 智能体入侵 Hugging Face 全过程：4 天半执行 17600 次操作",
        "url": "https://aihot.virxact.com/items/cms6r5fog0btjrohz9heu2c6f",
        "published": "Wed, 29 Jul 2026 23:29:34 GMT",
        "source": "IT之家（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "Replit Design 发布：AI 赋能设计愿景",
        "url": "https://aihot.virxact.com/items/cms6kdopf05tbrohzoim2kpeg",
        "published": "Wed, 29 Jul 2026 20:45:42 GMT",
        "source": "X：Replit (@Replit)",
        "time_ago": "今天"
      },
      {
        "title": "Claude Opus 5 在模拟售货机任务中展现欺骗与背叛，创下新纪录",
        "url": "https://aihot.virxact.com/items/cms6g4nn502errohzoxo9al2o",
        "published": "Wed, 29 Jul 2026 18:45:27 GMT",
        "source": "TechCrunch：AI（RSS）",
        "time_ago": "今天"
      },
      {
        "title": "Miles 在 Blackwell 架构上实现端到端 MXFP8 与逐 token NVFP4 强化学习方案",
        "url": "https://aihot.virxact.com/items/cms6drkj8001crohzuxf7kfy7",
        "published": "Wed, 29 Jul 2026 17:50:30 GMT",
        "source": "LMSYS：Blog（Chatbot Arena 团队）",
        "time_ago": "昨天"
      },
      {
        "title": "OpenAI 为学术研究者免费提供前沿模型",
        "url": "https://aihot.virxact.com/items/cms6cw5ha02sgrotzfmlr8p11",
        "published": "Wed, 29 Jul 2026 17:22:02 GMT",
        "source": "X：Sherwin Wu（@sherwinwu）",
        "time_ago": "昨天"
      },
      {
        "title": "Perplexity 开源智能体检测层 Numbat",
        "url": "https://aihot.virxact.com/items/cms6czboh031krotzmczxbw2v",
        "published": "Wed, 29 Jul 2026 17:01:42 GMT",
        "source": "X：Perplexity (@perplexity_ai)",
        "time_ago": "昨天"
      },
      {
        "title": "开源引擎可在任何 M 系列 Mac 上以 2 GB 内存运行 Gemma 4 26B",
        "url": "https://aihot.virxact.com/items/cms6arrc700rbrotzo1wseql3",
        "published": "Wed, 29 Jul 2026 16:09:22 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "昨天"
      }
    ],
    "one_company_news": [
      {
        "title": "上半年美股复盘：存储芯片半导体，K线虐我如蝼蚁",
        "url": "https://www.ximalaya.com/sound/1003587637",
        "published": "Wed, 29 Jul 2026 23:30:00 GMT",
        "author": "",
        "source": "亏钱指南",
        "time_ago": "今天",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6615cd1e5b4c7f0012fd9c7a"
      },
      {
        "title": "00后摆脱搞钱羞耻：做明星应援扇月入过万，摆摊穿戴甲日入五百",
        "url": "https://www.ximalaya.com/sound/1002371330",
        "published": "Wed, 22 Jul 2026 23:30:00 GMT",
        "author": "",
        "source": "亏钱指南",
        "time_ago": "1周前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6615cd1e5b4c7f0012fd9c7a"
      },
      {
        "title": "vol.53 对谈易立竞：折腾vs独处 极致对照组的两种活法答案",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a66487e6356eb2d9be8ca46?utm_source=rss",
        "published": "Mon, 27 Jul 2026 00:00:00 GMT",
        "author": "",
        "source": "天真不天真",
        "time_ago": "3天前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6473f1b85b4c7f0012fd9bf8"
      },
      {
        "title": "vol.52 对谈王安宇：十年可以让一个人发生多少变化",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a4a7af02e335a35a80e7c18?utm_source=rss",
        "published": "Mon, 06 Jul 2026 00:00:00 GMT",
        "author": "",
        "source": "天真不天真",
        "time_ago": "3周前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6473f1b85b4c7f0012fd9bf8"
      },
      {
        "title": "【截胡不截财】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/65e9c5e9d5e8d90013f65ab8",
        "source": "截胡不截财",
        "time_ago": "📱 点击在小宇宙App收听"
      },
      {
        "title": "269. 卷规模 VS 卷创作：真人短剧的两种生存模式",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a4f777d1e32575f5eb3cbc1?utm_source=rss",
        "published": "Thu, 09 Jul 2026 10:32:06 GMT",
        "author": "",
        "source": "乱翻书",
        "time_ago": "3周前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6416be6e5b4c7f0012fd9b86"
      },
      {
        "title": "268.AI时代，个人工作台会重新回到手机吗？",
        "url": "https://www.xiaoyuzhoufm.com/episode/6a3bdd319d2f5743683d4841?utm_source=rss",
        "published": "Wed, 24 Jun 2026 13:49:54 GMT",
        "author": "",
        "source": "乱翻书",
        "time_ago": "1月前",
        "xiaoyuzhou_url": "https://www.xiaoyuzhoufm.com/podcast/6416be6e5b4c7f0012fd9b86"
      }
    ]
  }
};
