#!/usr/bin/env python3
"""
修改 feishu_sync.py - 在 main() 末尾添加 dashboard_data.js 更新逻辑
自动找到正确的文件，自动处理各种结构
"""
import os, shutil, sys

# 自动搜索 feishu_sync.py
candidates = []
for root, dirs, files in os.walk(os.path.expanduser('~')):
    for f in files:
        if f == 'feishu_sync.py':
            candidates.append(os.path.join(root, f))

# 找最近修改的、包含 fetch_reading 的
target = None
for fp in sorted(candidates, key=os.path.getmtime, reverse=True):
    if os.path.exists(fp):
        try:
            c = open(fp).read()
            if 'def fetch_reading' in c:
                target = fp
                break
        except:
            pass

if not target:
    print("❌ 没找到目标文件")
    sys.exit(1)

print(f"✅ 找到: {target}")
c = open(target).read()

# 尝试找 if __name__ 或 main() 结束位置
marker = 'if __name__'
idx = c.rfind(marker)

if idx == -1:
    # 没有 if __name__，找 main() 函数的结束
    print("   没找到 if __name__，改为追加到文件末尾")
    idx = len(c)
else:
    print(f"   找到 if __name__ 在第 {c[:idx].count(chr(10))+1} 行")

insert_code = '''
    # ★ 同步阅读数据到 dashboard_data.js
    print("📝 同步阅读数据到 dashboard_data.js...")
    dashboard_path = os.path.join(WORKSPACE, 'feishu_data', 'dashboard_data.js')
    old_dashboard = {}
    if os.path.exists(dashboard_path):
        with open(dashboard_path, 'r', encoding='utf-8') as f:
            content2 = f.read()
            if 'const DASHBOARD_DATA' in content2:
                json_str = content2.split('const DASHBOARD_DATA = ', 1)[1]
                if json_str.endswith(';'):
                    json_str = json_str[:-1]
                try:
                    old_dashboard = json.loads(json_str)
                except:
                    pass
    reading = load_json('reading_data.json', {})
    if reading:
        old_dashboard['reading'] = {
            'challenge_days': reading.get('challenge_days', 0),
            'challenge_target': reading.get('challenge_target', 365),
            'rolling_day': reading.get('rolling_day', 0),
            'total_days': reading.get('total_days', 0),
            'weekly_read_time': reading.get('weekly_read_time', 0),
            'yesterday_read_time': reading.get('yesterday_read_time', 0),
            'total_read_hours': reading.get('total_read_hours', 0),
            'total_read_books': reading.get('total_read_books', 0),
            'total_finished_books': reading.get('total_finished_books', 0),
            'currently_reading': reading.get('currently_reading', []),
            'medals': reading.get('medals', []),
            'last_updated': reading.get('last_updated', ''),
        }
        new_content = (
            '// Auto-generated by feishu_sync.py at ' + datetime.now().isoformat() + '\\n'
            '// DO NOT EDIT MANUALLY\\n\\n'
            'const DASHBOARD_DATA = ' + json.dumps(old_dashboard, ensure_ascii=False, indent=2) + ';\\n'
        )
        os.makedirs(os.path.dirname(dashboard_path), exist_ok=True)
        with open(dashboard_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        print("  ✅ dashboard_data.js 已更新")

'''

new_content = c[:idx] + insert_code + c[idx:]
shutil.copy2(target, target + '.bak2')
open(target, 'w').write(new_content)
print("✅ 改动2完成！已备份到 .bak2")
