#!/usr/bin/env python3
"""
完整修复 feishu_sync.py - 恢复备份后重新应用所有改动
确保缩进正确
"""
import os, shutil, sys

# 搜索所有 feishu_sync.py
candidates = []
for root, dirs, files in os.walk(os.path.expanduser('~')):
    for f in files:
        if f == 'feishu_sync.py':
            candidates.append(os.path.join(root, f))

# 找有 .bak 备份的目标文件
target = None
for fp in candidates:
    bak = fp + '.bak'
    if os.path.exists(bak):
        try:
            c = open(fp).read()
            if 'def fetch_reading' in c:
                target = fp
                break
        except:
            pass

if not target:
    print("❌ 没找到带备份的目标文件")
    sys.exit(1)

print(f"✅ 找到: {target}")
print(f"   恢复备份: {target}.bak")

# 恢复备份
shutil.copy2(target + '.bak', target)
c = open(target).read()

# ── 改动1: 替换 weekly_read_time ──
lines = c.split('\n')
found = None
for i, line in enumerate(lines):
    if 'weekly_read_time' in line and 'challenge.get' in line:
        found = i
        break

if found is None:
    print("❌ 没找到 weekly_read_time")
    sys.exit(1)

print(f"   weekly_read_time 在第 {found+1} 行: {repr(lines[found])}")
print(f"   下一行: {repr(lines[found+1])}")

# 确定原文件缩进（从 weekly_read_time 那行提取）
leading = len(lines[found]) - len(lines[found].lstrip())
indent = lines[found][:leading]
print(f"   原文件缩进: {leading} 个空格")

# 找到 yesterday_read_time 那行的结束位置
end = found + 1
while end < len(lines) and 'yesterday_read_time' in lines[end]:
    end += 1

# 构建替换内容，使用原文件的缩进
def block(lines_list):
    return '\n'.join(indent + l if l else l for l in lines_list)

new_block = block([
    'weekly_read_time = None',
    'yesterday_read_time = None',
    'try:',
    "weekly_stats = call_weread_api('/readdata/detail', {'mode': 'weekly'})",
    'if weekly_stats:',
    "weekly_read_time = weekly_stats.get('readTime') or weekly_stats.get('weeklyReadTime')",
    'print(f"  ✅ 本周阅读时间（API）: {weekly_read_time}")',
    'except Exception as e:',
    'print(f"  ⚠️ 本周阅读时间 API 失败: {e}")',
    'try:',
    'yesterday = today - timedelta(days=1)',
    "yesterday_str = yesterday.strftime('%Y-%m-%d')",
    "daily_stats = call_weread_api('/readdata/detail', {'mode': 'daily', 'date': yesterday_str})",
    'if daily_stats:',
    "yesterday_read_time = daily_stats.get('readTime') or daily_stats.get('dailyReadTime')",
    'print(f"  ✅ 昨日阅读时间（API）: {yesterday_read_time}")',
    'except Exception as e:',
    'print(f"  ⚠️ 昨日阅读时间 API 失败: {e}")',
    'if weekly_read_time is None:',
    "weekly_read_time = challenge.get('weekly_read_time', 0)",
    'if yesterday_read_time is None:',
    "yesterday_read_time = challenge.get('yesterday_read_time', 0)",
])

new_content = '\n'.join(lines[:found] + [new_block] + lines[end:])

# ── 改动2: 在 if __name__ 前插入 dashboard_data 更新 ──
marker = 'if __name__'
idx = new_content.rfind(marker)

insert_lines = [
    '',
    indent + '# ★ 同步阅读数据到 dashboard_data.js',
    indent + 'print("📝 同步阅读数据到 dashboard_data.js...")',
    indent + "dashboard_path = os.path.join(WORKSPACE, 'feishu_data', 'dashboard_data.js')",
    indent + 'old_dashboard = {}',
    indent + 'if os.path.exists(dashboard_path):',
    indent + "    with open(dashboard_path, 'r', encoding='utf-8') as f:",
    indent + '        content2 = f.read()',
    indent + "        if 'const DASHBOARD_DATA' in content2:",
    indent + "            json_str = content2.split('const DASHBOARD_DATA = ', 1)[1]",
    indent + "            if json_str.endswith(';'):",
    indent + '                json_str = json_str[:-1]',
    indent + '            try:',
    indent + '                old_dashboard = json.loads(json_str)',
    indent + '            except:',
    indent + '                pass',
    indent + "reading = load_json('reading_data.json', {})",
    indent + 'if reading:',
    indent + "    old_dashboard['reading'] = {",
    indent + "        'challenge_days': reading.get('challenge_days', 0),",
    indent + "        'challenge_target': reading.get('challenge_target', 365),",
    indent + "        'rolling_day': reading.get('rolling_day', 0),",
    indent + "        'total_days': reading.get('total_days', 0),",
    indent + "        'weekly_read_time': reading.get('weekly_read_time', 0),",
    indent + "        'yesterday_read_time': reading.get('yesterday_read_time', 0),",
    indent + "        'total_read_hours': reading.get('total_read_hours', 0),",
    indent + "        'total_read_books': reading.get('total_read_books', 0),",
    indent + "        'total_finished_books': reading.get('total_finished_books', 0),",
    indent + "        'currently_reading': reading.get('currently_reading', []),",
    indent + "        'medals': reading.get('medals', []),",
    indent + "        'last_updated': reading.get('last_updated', ''),",
    indent + '    }',
    indent + '    new_dash = (',
    indent + "        '// Auto-generated by feishu_sync.py at ' + datetime.now().isoformat() + '\\\\n'",
    indent + "        '// DO NOT EDIT MANUALLY\\\\n\\\\n'",
    indent + "        'const DASHBOARD_DATA = ' + json.dumps(old_dashboard, ensure_ascii=False, indent=2) + ';\\\\n'",
    indent + '    )',
    indent + '    os.makedirs(os.path.dirname(dashboard_path), exist_ok=True)',
    indent + "    with open(dashboard_path, 'w', encoding='utf-8') as f:",
    indent + '        f.write(new_dash)',
    indent + '    print("  ✅ dashboard_data.js 已更新")',
    '',
]

insert_code = '\n'.join(insert_lines)

if idx >= 0:
    new_content = new_content[:idx] + insert_code + new_content[idx:]
else:
    new_content = new_content + insert_code

# 写入
shutil.copy2(target, target + '.bak4')
open(target, 'w').write(new_content)
print("✅ 完整修复完成！已备份到 .bak4")

# 验证语法
import py_compile
try:
    py_compile.compile(target, doraise=True)
    print("✅ 语法检查通过！")
except py_compile.PyCompileError as e:
    print(f"❌ 语法错误: {e}")
