#!/usr/bin/env python3
"""
完整修复 feishu_sync.py - 恢复备份后重新应用所有改动
"""
import os, shutil, sys

# 搜索所有 feishu_sync.py
candidates = []
for root, dirs, files in os.walk(os.path.expanduser('~')):
    for f in files:
        if f == 'feishu_sync.py':
            candidates.append(os.path.join(root, f))

# 找有 .bak 备份的目标文件
target = None
for fp in candidates:
    bak = fp + '.bak'
    if os.path.exists(bak):
        try:
            c = open(fp).read()
            if 'def fetch_reading' in c:
                target = fp
                break
        except:
            pass

if not target:
    print("❌ 没找到带备份的目标文件")
    sys.exit(1)

print(f"✅ 找到: {target}")
print(f"   恢复备份: {target}.bak")

# 恢复备份
shutil.copy2(target + '.bak', target)
c = open(target).read()

# ── 改动1: 替换 weekly_read_time ──
lines = c.split('\n')
found = None
for i, line in enumerate(lines):
    if 'weekly_read_time' in line and 'challenge.get' in line:
        found = i
        break

if found is None:
    print("❌ 没找到 weekly_read_time")
    sys.exit(1)

print(f"   weekly_read_time 在第 {found+1} 行")

# 找到 yesterday_read_time 那行的结束位置
end = found + 1
while end < len(lines) and 'yesterday_read_time' in lines[end]:
    end += 1

new_block = '''    weekly_read_time = None
    yesterday_read_time = None
    try:
        weekly_stats = call_weread_api('/readdata/detail', {'mode': 'weekly'})
        if weekly_stats:
            weekly_read_time = weekly_stats.get('readTime') or weekly_stats.get('weeklyReadTime')
            print(f"  ✅ 本周阅读时间（API）: {weekly_read_time}")
    except Exception as e:
        print(f"  ⚠️ 本周阅读时间 API 失败: {e}")
    try:
        yesterday = today - timedelta(days=1)
        yesterday_str = yesterday.strftime('%Y-%m-%d')
        daily_stats = call_weread_api('/readdata/detail', {'mode': 'daily', 'date': yesterday_str})
        if daily_stats:
            yesterday_read_time = daily_stats.get('readTime') or daily_stats.get('dailyReadTime')
            print(f"  ✅ 昨日阅读时间（API）: {yesterday_read_time}")
    except Exception as e:
        print(f"  ⚠️ 昨日阅读时间 API 失败: {e}")
    if weekly_read_time is None:
        weekly_read_time = challenge.get('weekly_read_time', 0)
    if yesterday_read_time is None:
        yesterday_read_time = challenge.get('yesterday_read_time', 0)
'''

new_lines_list = new_block.rstrip('\n').split('\n')
new_content = '\n'.join(lines[:found] + new_lines_list + lines[end:])

# ── 改动2: 在 if __name__ 前插入 dashboard_data 更新 ──
marker = 'if __name__'
idx = new_content.rfind(marker)

insert_code = '''    # ★ 同步阅读数据到 dashboard_data.js
    print("📝 同步阅读数据到 dashboard_data.js...")
    dashboard_path = os.path.join(WORKSPACE, 'feishu_data', 'dashboard_data.js')
    old_dashboard = {}
    if os.path.exists(dashboard_path):
        with open(dashboard_path, 'r', encoding='utf-8') as f:
            content2 = f.read()
            if 'const DASHBOARD_DATA' in content2:
                json_str = content2.split('const DASHBOARD_DATA = ', 1)[1]
                if json_str.endswith(';'):
                    json_str = json_str[:-1]
                try:
                    old_dashboard = json.loads(json_str)
                except:
                    pass
    reading = load_json('reading_data.json', {})
    if reading:
        old_dashboard['reading'] = {
            'challenge_days': reading.get('challenge_days', 0),
            'challenge_target': reading.get('challenge_target', 365),
            'rolling_day': reading.get('rolling_day', 0),
            'total_days': reading.get('total_days', 0),
            'weekly_read_time': reading.get('weekly_read_time', 0),
            'yesterday_read_time': reading.get('yesterday_read_time', 0),
            'total_read_hours': reading.get('total_read_hours', 0),
            'total_read_books': reading.get('total_read_books', 0),
            'total_finished_books': reading.get('total_finished_books', 0),
            'currently_reading': reading.get('currently_reading', []),
            'medals': reading.get('medals', []),
            'last_updated': reading.get('last_updated', ''),
        }
        new_dash = (
            '// Auto-generated by feishu_sync.py at ' + datetime.now().isoformat() + '\\n'
            '// DO NOT EDIT MANUALLY\\n\\n'
            'const DASHBOARD_DATA = ' + json.dumps(old_dashboard, ensure_ascii=False, indent=2) + ';\\n'
        )
        os.makedirs(os.path.dirname(dashboard_path), exist_ok=True)
        with open(dashboard_path, 'w', encoding='utf-8') as f:
            f.write(new_dash)
        print("  ✅ dashboard_data.js 已更新")

'''

if idx >= 0:
    new_content = new_content[:idx] + insert_code + new_content[idx:]
else:
    new_content = new_content + insert_code

# 写入
shutil.copy2(target, target + '.bak3')
open(target, 'w').write(new_content)
print("✅ 完整修复完成！已备份到 .bak3")

# 验证语法
import py_compile
try:
    py_compile.compile(target, doraise=True)
    print("✅ 语法检查通过！")
except py_compile.PyCompileError as e:
    print(f"❌ 语法错误: {e}")
