// Auto-generated by feishu_sync.py
// Last updated: 2026-08-05 14:54
window.DASHBOARD_DATA = {
  "tasks": {
    "date": "8月5日",
    "items": [
      {
        "text": "运动1小时",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "给韩莹买生日礼物",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "写10篇小红书笔记（本周的笔记都完成）",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "完善孕期工作台，这样就可以写1篇笔记分享了",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "上架新产品，做 3 个 sku",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "看一下flova网站怎么用",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_text": "1.运动1小时\n2.给韩莹买生日礼物\n3.写10篇小红书笔记（本周的笔记都完成）\n4.完善孕期工作台，这样就可以写1篇笔记分享了\n5.上架新产品，做 3 个 sku\n6.看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材\n7.看一下flova网站怎么用",
    "tasks": [
      {
        "text": "运动1小时",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "给韩莹买生日礼物",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "写10篇小红书笔记（本周的笔记都完成）",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "完善孕期工作台，这样就可以写1篇笔记分享了",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "上架新产品，做 3 个 sku",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材",
        "done": false,
        "cancelled": false,
        "priority": "low"
      },
      {
        "text": "看一下flova网站怎么用",
        "done": false,
        "cancelled": false,
        "priority": "low"
      }
    ],
    "raw_tasks_text": "1.运动1小时\n2.给韩莹买生日礼物\n3.写10篇小红书笔记（本周的笔记都完成）\n4.完善孕期工作台，这样就可以写1篇笔记分享了\n5.上架新产品，做 3 个 sku\n6.看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材\n7.看一下flova网站怎么用"
  },
  "memos": {
    "items": [
      {
        "date": "7月31日",
        "text": "买个摄像头回家（放客厅看爸妈小耳朵）",
        "id": "memo_39_1"
      },
      {
        "date": "7月31日",
        "text": "小程序开发，等做好了小程序再一步步操作",
        "id": "memo_39_0"
      },
      {
        "date": "7月29日",
        "text": "流产后身心恢复指南，卖的更好，是不是可以继续开发类似的产品",
        "id": "memo_37_1"
      },
      {
        "date": "7月29日",
        "text": "孕期记录工作台：用 Workbuddy 搭孕期记录工具，先分享，如果很多人不会用可以打包成 skill 出售",
        "id": "memo_37_0"
      },
      {
        "date": "7月28日",
        "text": "学习红十字会急救培训课程",
        "id": "memo_36_7"
      },
      {
        "date": "7月28日",
        "text": "看3个AI分享大会",
        "id": "memo_36_6"
      },
      {
        "date": "7月28日",
        "text": "实践张咋啦分享的各类AI产品",
        "id": "memo_36_5"
      },
      {
        "date": "7月28日",
        "text": "孕期知识库，后续可考虑逐步补充待产包、准爸爸参与手册、怀孕书单读书笔记、孕吐缓解指南（正好可以保持持续更新的卖点）",
        "id": "memo_36_4"
      },
      {
        "date": "7月28日",
        "text": "参考松月的养生知识库做一个孕期食谱（不一定卖主要是为了操作一遍）",
        "id": "memo_36_3"
      },
      {
        "date": "7月28日",
        "text": "研究并搞懂小程序开发的流程和各种概念",
        "id": "memo_36_2"
      }
    ],
    "total": 10
  },
  "inspirations": {
    "items": [
      {
        "date": "6月24日",
        "inspiration": "",
        "harvest": "",
        "task": "",
        "mood": "test full range"
      },
      {
        "date": "7月27日",
        "inspiration": "",
        "harvest": "让AI直接读取我的飞书选题表格，做好排期后，让它一键写笔记，不用我再一个个选题发给它们了",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月28日",
        "inspiration": "",
        "harvest": "1.学会了借助skill优化网站\n2.发现了飞书字段有一个【字段捷径中心】，可以把现有字段转换为其他想要的字段形式，比如日期变成年月\n3.把做人生系统个人网站的经验封装成了life-dashboard-builder Skill",
        "task": "",
        "mood": ""
      },
      {
        "date": "7月30日",
        "inspiration": "",
        "harvest": "",
        "task": "1.挂周一的号-北京妇产医院\n2.买山药粉\n3.做鸡肉干",
        "mood": ""
      },
      {
        "date": "7月31日",
        "inspiration": "",
        "harvest": "孕期知识库是我的第一个产品，不一定是我人生唯一产品",
        "task": "1.买山药粉\n2.确认一下 AI 资讯数据来源和已发布笔记数据是否正确",
        "mood": ""
      },
      {
        "date": "8月1日",
        "inspiration": "",
        "harvest": "",
        "task": "1.和杜爽爽视频\n2.调研一下爆款笔记，关键词：生育、成为妈妈、怀孕",
        "mood": ""
      },
      {
        "date": "8月3日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.把我的人生系统这个网站做一下优化迭代",
        "mood": ""
      },
      {
        "date": "8月5日",
        "inspiration": "",
        "harvest": "",
        "task": "1.上架新产品，做 3 个 sku\n2.看有什么渠道/网站提升审美，现在作图和网页真的需要审美和提供给 AI 的素材\n3.扫地",
        "mood": ""
      }
    ],
    "last_updated": "6月24日",
    "today_updated": true
  },
  "finance": {
    "year_income": "¥551,774",
    "year_expense": "¥236,821",
    "monthly_data": [
      {
        "month": "2026年1月",
        "income": 91873.0,
        "expense": 29618.52
      },
      {
        "month": "2026年2月",
        "income": 39100.0,
        "expense": 46365.75
      },
      {
        "month": "2026年3月",
        "income": 37290.86,
        "expense": 40501.47
      },
      {
        "month": "2026年4月",
        "income": 39337.92,
        "expense": 40147.7
      },
      {
        "month": "2026年5月",
        "income": 276369.07,
        "expense": 29135.81
      },
      {
        "month": "2026年6月",
        "income": 33091.87,
        "expense": 27747.77
      }
    ],
    "yesterday_expense": "¥79.80",
    "last_updated": "2026-08-05",
    "last_month_expense": "¥23,304.58",
    "last_month_income": "¥34,711.87",
    "month_expense_to_yesterday": "¥246.71",
    "income_annual": 24973,
    "income_ytd": 24973.0
  },
  "reading": {
    "challenge_days": 150,
    "challenge_target": 365,
    "rolling_day": 150,
    "total_days": 1110,
    "weekly_read_time": 97,
    "yesterday_read_time": 40,
    "total_read_hours": 454,
    "total_read_books": 150,
    "currently_reading": [
      {
        "title": "听段涛聊孕事",
        "author": "段涛",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-05",
        "created": "2026-08-05"
      },
      {
        "title": "我怎么这么会当妈",
        "author": "格十三",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-08-01",
        "created": "2026-08-01"
      },
      {
        "title": "他者中的华人：中国近现代移民史",
        "author": "孔飞力",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-07-31",
        "created": "2026-07-31"
      },
      {
        "title": "孩子王（轻经典）",
        "author": "阿城",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-07-27",
        "created": "2026-07-27"
      },
      {
        "title": "毛泽东选集（全四卷）",
        "author": "",
        "status": "在读",
        "progress": 0,
        "last_read": "2026-07-26",
        "created": "2026-07-26"
      }
    ],
    "medals": [
      {
        "id": "M7-0-200",
        "type": 7,
        "subtype": 0,
        "level": 200,
        "ctime": 1783829092,
        "atime": 1783839061,
        "rank": 644409,
        "users": 650822,
        "hint": "想法发布 200 条",
        "renderItem": "07 / 12",
        "name": "想法发布",
        "index": 0,
        "availableCond": "累积达到200条",
        "tip": "再发表 0 条想法可得",
        "title": "想法发布",
        "rankText": "第644409位获得此勋章的书友",
        "displayText": "想法发布 200 条"
      },
      {
        "id": "M1-0-90",
        "type": 1,
        "subtype": 0,
        "level": 90,
        "ctime": 1778297612,
        "atime": 1778297636,
        "rank": 1894417,
        "users": 1932917,
        "hint": "连续阅读 90 天",
        "renderItem": "05 / 09",
        "name": "连续阅读",
        "index": 1,
        "availableCond": "累积达到90天",
        "tip": "再连续阅读 65 天可得",
        "title": "连续阅读",
        "rankText": "第1894417位获得此勋章的书友",
        "displayText": "连续阅读 90 天"
      },
      {
        "id": "M12-2-3-I-0-0-0",
        "type": 12,
        "subtype": 2,
        "level": 0,
        "ctime": 1776906259,
        "atime": 1776906259,
        "rank": 102178,
        "users": 472590,
        "hint": "你与华夏的文字格外投缘",
        "renderItem": "04 / 23",
        "name": "世界读书日",
        "index": 2,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "世界读书日",
        "rankText": "第102178位获得此勋章的书友",
        "displayText": "山水行吟客",
        "styleType": 1,
        "styleTitle": "山水行吟客",
        "styleDesc": "你与华夏的文字格外投缘"
      },
      {
        "id": "M3-0-1000",
        "type": 3,
        "subtype": 0,
        "level": 1000,
        "ctime": 1776347296,
        "atime": 1776347477,
        "rank": 1755752,
        "users": 1806165,
        "hint": "阅读 1000 天",
        "renderItem": "04 / 16",
        "name": "阅读天数",
        "index": 3,
        "availableCond": "累积达到1000天",
        "tip": "再阅读 0 天可得",
        "title": "阅读天数",
        "rankText": "第1755752位获得此勋章的书友",
        "displayText": "阅读 1000 天"
      },
      {
        "id": "M15-2-0",
        "type": 15,
        "subtype": 2,
        "level": 0,
        "ctime": 1774972748,
        "atime": 1774972748,
        "rank": 697853,
        "users": 794866,
        "hint": "21天阅读挑战",
        "renderItem": "03 / 31",
        "name": "21天阅读挑战",
        "index": 4,
        "availableCond": "完成挑战任务可得",
        "tip": "",
        "title": "21天阅读挑战",
        "rankText": "成功挑战2次 · 第697853位获得此勋章的书友",
        "displayText": "21天阅读挑战"
      }
    ],
    "last_updated": "2026-08-05",
    "total_finished_books": 65,
    "weekly_data": {
      "weekly_read_time": 97,
      "yesterday_read_time": 40,
      "source": "周数据"
    },
    "total_data": {
      "total_read_hours": 454,
      "total_read_books": 150,
      "total_finished_books": 65,
      "source": "总数据"
    }
  },
  "published_notes": {
    "total": 114,
    "last_updated": "2026-08-05",
    "month_count": 3
  },
  "exercise": {
    "month": "2026年7月",
    "month_key": "2026-07",
    "month_label": "7月",
    "week_header": [
      "一",
      "二",
      "三",
      "四",
      "五",
      "六",
      "日"
    ],
    "exercise_blocks": [
      {
        "emoji": "🧘",
        "name": "体态矫正",
        "color": "#FF6B9D",
        "videos": [
          {
            "title": "【欧阳春晓】15min告别肩背肥厚",
            "bvid": "BV1Qv411t7EN",
            "duration": "15:00"
          },
          {
            "title": "MIZI · 改善圆肩驼背｜跟练版",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "12:00"
          },
          {
            "title": "骨盆前倾矫正｜每天10分钟",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          }
        ]
      },
      {
        "emoji": "🔥",
        "name": "燃脂训练",
        "color": "#FF9F43",
        "videos": [
          {
            "title": "帕梅拉 · 15min全身燃脂｜暴汗",
            "bvid": "BV1qK4y1t7fP",
            "duration": "15:00"
          },
          {
            "title": "Eleni Fit · 30min站立燃脂｜新手友好",
            "bvid": "BV1GJ411x7h7",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 14天瘦大腿内侧｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "28:00"
          }
        ]
      },
      {
        "emoji": "💪",
        "name": "力量塑形",
        "color": "#4ECDC4",
        "videos": [
          {
            "title": "蜜桃臀养成 · 31min跟练版",
            "bvid": "BV1GJ411x7h7",
            "duration": "31:00"
          },
          {
            "title": "Barre · 30min肩背塑形",
            "bvid": "BV1qK4y1t7fP",
            "duration": "30:00"
          },
          {
            "title": "MIZI · 2周瘦手臂｜day1",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "21:00"
          }
        ]
      },
      {
        "emoji": "🫁",
        "name": "拉伸放松",
        "color": "#A29BFE",
        "videos": [
          {
            "title": "全身拉伸放松 · 10min",
            "bvid": "BV1GJ411x7h7",
            "duration": "10:00"
          },
          {
            "title": "腿部拉伸 · 睡前10min",
            "bvid": "BV1qK4y1t7fP",
            "duration": "10:00"
          },
          {
            "title": "阴瑜伽 · 放松30min",
            "bvid": "BV1kN4y1E7Xa",
            "duration": "30:00"
          }
        ]
      }
    ]
  },
  "oneCompany": {
    "total_revenue": "¥192.9",
    "total_orders": 11,
    "products": [
      {
        "name": "孕期安心知识库",
        "price": "¥39.9"
      },
      {
        "name": "产后恢复指南",
        "price": "¥9.9"
      }
    ],
    "total_published_notes": 114,
    "monthly_revenue": [],
    "weekly_revenue": [
      {
        "label": "6/29",
        "revenue": 39.9
      },
      {
        "label": "7/6",
        "revenue": 89.4
      },
      {
        "label": "7/13",
        "revenue": 49.8
      },
      {
        "label": "7/20",
        "revenue": 0
      },
      {
        "label": "7/27",
        "revenue": 13.8
      },
      {
        "label": "8/3",
        "revenue": 0
      }
    ],
    "last_updated": "2026-08-05"
  },
  "hotTopics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 医生，我咋算自己是哪天怀孕的？|有点小事61",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "今天"
      },
      {
        "title": "🎙 嗨咻 | 100. 为什么越想表现自己，越容易在社交中露怯？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "6天前"
      },
      {
        "title": "🎙 头回当妈 | 100. 特别节目｜头回当妈的101问 第一弹",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 畅所育言 | 111 专访大理溪谷小人国园长：在大理，我们不说幼儿园，我们聊儿童成长社区",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "2天前"
      },
      {
        "title": "🎙 Alison Yu心理 | ep90 | 边界：主体性的表达，真实关系的开始",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "2周前"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-08-05",
    "ai_news": [
      {
        "title": "Qwen-Image-3.0-Pro 上线 Qwen Cloud",
        "url": "https://aihot.virxact.com/items/cmsficgoy000nrochjow7i1yx",
        "published": "Wed, 05 Aug 2026 02:40:31 GMT",
        "source": "X：通义千问 / Qwen (@Alibaba_Qwen)",
        "time_ago": "今天"
      },
      {
        "title": "开源「活人感写作.skill」：一个帮你写出没有AI味的文字的通用写作技能",
        "url": "https://aihot.virxact.com/items/cmsff72yv1q6nro2etf4cmbuj",
        "published": "Wed, 05 Aug 2026 01:35:42 GMT",
        "source": "公众号：数字生命卡兹克",
        "time_ago": "今天"
      },
      {
        "title": "LLM 0.32 发布：新增推理轨迹、OpenAI Responses、服务端工具与更智能的日志",
        "url": "https://aihot.virxact.com/items/cmsfdkkcs1ocxro2ed4z3s131",
        "published": "Tue, 04 Aug 2026 23:58:24 GMT",
        "source": "Simon Willison 博客",
        "time_ago": "今天"
      },
      {
        "title": "Replit 环境智能：免提示词自动生成设计",
        "url": "https://aihot.virxact.com/items/cmsf7gr271ii5ro2eiu0hihb5",
        "published": "Tue, 04 Aug 2026 22:00:10 GMT",
        "source": "X：Replit (@Replit)",
        "time_ago": "今天"
      },
      {
        "title": "MiniMax-H3 通过 MLX 移植可在 Apple Silicon 上运行",
        "url": "https://aihot.virxact.com/items/cmsf2ukfc1ekiro2e4h0k2bux",
        "published": "Tue, 04 Aug 2026 19:10:09 GMT",
        "source": "Simon Willison 博客",
        "time_ago": "今天"
      },
      {
        "title": "Soup v0.72.4：在4 GB显存笔记本GPU上微调8B模型",
        "url": "https://aihot.virxact.com/items/cmsezylz31cadro2eoq1np3vh",
        "published": "Tue, 04 Aug 2026 18:17:29 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "今天"
      },
      {
        "title": "OpenRouter 上线 FLUX 3 Video 统一多模态模型",
        "url": "https://aihot.virxact.com/items/cmseyrhcj1bgmro2ed47t5b0k",
        "published": "Tue, 04 Aug 2026 17:54:06 GMT",
        "source": "X：OpenRouter (@OpenRouter)",
        "time_ago": "今天"
      },
      {
        "title": "SpecForge v0.3.0 发布：统一解耦与共置投机解码栈，新增开放 SpecBundle 草稿模型",
        "url": "https://aihot.virxact.com/items/cmseyfjcz1au8ro2enx0b7os6",
        "published": "Tue, 04 Aug 2026 17:51:09 GMT",
        "source": "LMSYS：Blog（Chatbot Arena 团队）",
        "time_ago": "今天"
      },
      {
        "title": "GitHub 如何用堆叠式 Pull Request 拆解 AI 生成的巨型代码",
        "url": "https://aihot.virxact.com/items/cmsewck8518x6ro2e32q4bksr",
        "published": "Tue, 04 Aug 2026 16:47:18 GMT",
        "source": "GitHub Blog",
        "time_ago": "今天"
      },
      {
        "title": "Google Cloud API Gateway 推出统一模型路由功能，支持 Gemini、Claude 与 OpenAI OSS-GPT",
        "url": "https://aihot.virxact.com/items/cmsew3l4y18qhro2edk0yaat8",
        "published": "Tue, 04 Aug 2026 16:45:02 GMT",
        "source": "Google Developers Blog（RSS）",
        "time_ago": "今天"
      }
    ],
    "one_company_news": [
      {
        "title": "AI时代，依然是药明康德的“黄金时代”",
        "url": "https://www.tmtpost.com/8091097.html",
        "published": "Wed, 05 Aug 2026 11:35:08 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "鸿蒙智行发布「竹知了」相关情况说明；小红书封禁 AI 毒动画，未成年陪聊等 10 万账号；马斯克财富缩水2.45万亿元｜极客早知道",
        "url": "http://www.geekpark.net/news/368389",
        "published": "Wed, 05 Aug 2026 08:13:50 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "31.98 万元的腾势 Z9S，开始为腾势「去登味」",
        "url": "https://www.ifanr.com/1673908?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Wed, 05 Aug 2026 01:53:50 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "last_sync": "2026-08-05 14:54",
  "expense_categories": {
    "items": [
      {
        "rank": 1,
        "category": "房贷",
        "emoji": "🏠",
        "amount": "¥7,927",
        "amount_raw": 7927.4,
        "percent": 100
      },
      {
        "rank": 2,
        "category": "房租",
        "emoji": "🏠",
        "amount": "¥4,530",
        "amount_raw": 4530.0,
        "percent": 57
      },
      {
        "rank": 3,
        "category": "赵晗支出",
        "emoji": "👤",
        "amount": "¥3,518",
        "amount_raw": 3518.07,
        "percent": 44
      },
      {
        "rank": 4,
        "category": "固定支出",
        "emoji": "🔒",
        "amount": "¥2,667",
        "amount_raw": 2667.27,
        "percent": 34
      },
      {
        "rank": 5,
        "category": "公交打车",
        "emoji": "📌",
        "amount": "¥1,266",
        "amount_raw": 1266.0700000000002,
        "percent": 16
      },
      {
        "rank": 6,
        "category": "零食奶茶",
        "emoji": "📌",
        "amount": "¥926",
        "amount_raw": 926.73,
        "percent": 12
      },
      {
        "rank": 7,
        "category": "一日三餐",
        "emoji": "🍽️",
        "amount": "¥884",
        "amount_raw": 884.7199999999999,
        "percent": 11
      }
    ],
    "month": "2026年7月",
    "last_updated": "2026-08-05"
  },
  "hot_topics": {
    "user_pain_points": [
      {
        "title": "孕早期10个没人告诉你的秘密，过来人：早知道少遭多少罪！",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "孕期博主涨粉必备！15个小红书爆款标题套路",
        "category": "运营技巧",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "NT秒过经验！这三句话千万要跟医生提前说",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "建档花了2000才明白的事……这些检查真不用做",
        "category": "产检攻略",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "孕反严重时，老公买的这5样让我活过来了",
        "category": "孕吐缓解",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "准爸爸在孕期到底该做什么？一份实用清单",
        "category": "准爸爸",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "以为孕吐正常，结果差点送急诊！这些信号必须警惕",
        "category": "孕早期",
        "source": "小红书",
        "hotness": "🔥🔥"
      },
      {
        "title": "怀孕不是变脆弱，而是被迫变敏感",
        "category": "情绪管理",
        "source": "小红书",
        "hotness": "🔥🔥🔥"
      },
      {
        "title": "🎙 【艾屿回声】最新节目",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67bfd11326055d2fe7bcc8bd",
        "source": "艾屿回声",
        "category": "播客",
        "hotness": "🎧"
      },
      {
        "title": "🎙 当个事儿 | 医生，我咋算自己是哪天怀孕的？|有点小事61",
        "url": "https://www.xiaoyuzhoufm.com/podcast/60d2d172afc14743da181066",
        "source": "当个事儿",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "今天"
      },
      {
        "title": "🎙 嗨咻 | 100. 为什么越想表现自己，越容易在社交中露怯？",
        "url": "https://www.xiaoyuzhoufm.com/podcast/631812fe43274df80456d001",
        "source": "嗨咻",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "6天前"
      },
      {
        "title": "🎙 头回当妈 | 100. 特别节目｜头回当妈的101问 第一弹",
        "url": "https://www.xiaoyuzhoufm.com/podcast/6484fbe126fd9f4b4347ad04",
        "source": "头回当妈",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "1周前"
      },
      {
        "title": "🎙 畅所育言 | 111 专访大理溪谷小人国园长：在大理，我们不说幼儿园，我们聊儿童成长社区",
        "url": "https://www.xiaoyuzhoufm.com/podcast/64d25bd580c9ec4c5fbb0da4",
        "source": "畅所育言",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "2天前"
      },
      {
        "title": "🎙 Alison Yu心理 | ep90 | 边界：主体性的表达，真实关系的开始",
        "url": "https://www.xiaoyuzhoufm.com/podcast/67c8dd34d6c2a59e23f2d932",
        "source": "Alison Yu心理",
        "category": "播客",
        "hotness": "🎧",
        "time_ago": "2周前"
      }
    ],
    "keywords": [
      "怀孕",
      "孕早期",
      "流产",
      "备孕",
      "准爸爸",
      "产检",
      "生育",
      "孕吐"
    ],
    "last_updated": "2026-08-05",
    "ai_news": [
      {
        "title": "Qwen-Image-3.0-Pro 上线 Qwen Cloud",
        "url": "https://aihot.virxact.com/items/cmsficgoy000nrochjow7i1yx",
        "published": "Wed, 05 Aug 2026 02:40:31 GMT",
        "source": "X：通义千问 / Qwen (@Alibaba_Qwen)",
        "time_ago": "今天"
      },
      {
        "title": "开源「活人感写作.skill」：一个帮你写出没有AI味的文字的通用写作技能",
        "url": "https://aihot.virxact.com/items/cmsff72yv1q6nro2etf4cmbuj",
        "published": "Wed, 05 Aug 2026 01:35:42 GMT",
        "source": "公众号：数字生命卡兹克",
        "time_ago": "今天"
      },
      {
        "title": "LLM 0.32 发布：新增推理轨迹、OpenAI Responses、服务端工具与更智能的日志",
        "url": "https://aihot.virxact.com/items/cmsfdkkcs1ocxro2ed4z3s131",
        "published": "Tue, 04 Aug 2026 23:58:24 GMT",
        "source": "Simon Willison 博客",
        "time_ago": "今天"
      },
      {
        "title": "Replit 环境智能：免提示词自动生成设计",
        "url": "https://aihot.virxact.com/items/cmsf7gr271ii5ro2eiu0hihb5",
        "published": "Tue, 04 Aug 2026 22:00:10 GMT",
        "source": "X：Replit (@Replit)",
        "time_ago": "今天"
      },
      {
        "title": "MiniMax-H3 通过 MLX 移植可在 Apple Silicon 上运行",
        "url": "https://aihot.virxact.com/items/cmsf2ukfc1ekiro2e4h0k2bux",
        "published": "Tue, 04 Aug 2026 19:10:09 GMT",
        "source": "Simon Willison 博客",
        "time_ago": "今天"
      },
      {
        "title": "Soup v0.72.4：在4 GB显存笔记本GPU上微调8B模型",
        "url": "https://aihot.virxact.com/items/cmsezylz31cadro2eoq1np3vh",
        "published": "Tue, 04 Aug 2026 18:17:29 GMT",
        "source": "Hacker News 热门（buzzing.cc 中文翻译）",
        "time_ago": "今天"
      },
      {
        "title": "OpenRouter 上线 FLUX 3 Video 统一多模态模型",
        "url": "https://aihot.virxact.com/items/cmseyrhcj1bgmro2ed47t5b0k",
        "published": "Tue, 04 Aug 2026 17:54:06 GMT",
        "source": "X：OpenRouter (@OpenRouter)",
        "time_ago": "今天"
      },
      {
        "title": "SpecForge v0.3.0 发布：统一解耦与共置投机解码栈，新增开放 SpecBundle 草稿模型",
        "url": "https://aihot.virxact.com/items/cmseyfjcz1au8ro2enx0b7os6",
        "published": "Tue, 04 Aug 2026 17:51:09 GMT",
        "source": "LMSYS：Blog（Chatbot Arena 团队）",
        "time_ago": "今天"
      },
      {
        "title": "GitHub 如何用堆叠式 Pull Request 拆解 AI 生成的巨型代码",
        "url": "https://aihot.virxact.com/items/cmsewck8518x6ro2e32q4bksr",
        "published": "Tue, 04 Aug 2026 16:47:18 GMT",
        "source": "GitHub Blog",
        "time_ago": "今天"
      },
      {
        "title": "Google Cloud API Gateway 推出统一模型路由功能，支持 Gemini、Claude 与 OpenAI OSS-GPT",
        "url": "https://aihot.virxact.com/items/cmsew3l4y18qhro2edk0yaat8",
        "published": "Tue, 04 Aug 2026 16:45:02 GMT",
        "source": "Google Developers Blog（RSS）",
        "time_ago": "今天"
      }
    ],
    "one_company_news": [
      {
        "title": "AI时代，依然是药明康德的“黄金时代”",
        "url": "https://www.tmtpost.com/8091097.html",
        "published": "Wed, 05 Aug 2026 11:35:08 +0800",
        "author": "",
        "source": "钛媒体",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "鸿蒙智行发布「竹知了」相关情况说明；小红书封禁 AI 毒动画，未成年陪聊等 10 万账号；马斯克财富缩水2.45万亿元｜极客早知道",
        "url": "http://www.geekpark.net/news/368389",
        "published": "Wed, 05 Aug 2026 08:13:50 +0800",
        "author": "",
        "source": "极客公园",
        "time_ago": "今天",
        "category": "资讯"
      },
      {
        "title": "31.98 万元的腾势 Z9S，开始为腾势「去登味」",
        "url": "https://www.ifanr.com/1673908?utm_source=rss&utm_medium=rss&utm_campaign=",
        "published": "Wed, 05 Aug 2026 01:53:50 +0000",
        "author": "",
        "source": "爱范儿",
        "time_ago": "今天",
        "category": "资讯"
      }
    ]
  },
  "weather": {
    "cities": {
      "beijing": {
        "name": "北京 · 顺义",
        "temp": 33.1,
        "weather_code": 0,
        "desc": "☀️ 晴",
        "min": 24.8,
        "max": 35.2
      },
      "wuhan": {
        "name": "武汉 · 洪山",
        "temp": 35.4,
        "weather_code": 0,
        "desc": "☀️ 晴",
        "min": 27.9,
        "max": 35.5
      }
    },
    "last_updated": "2026-08-05 12:27"
  },
  "inspirations_done": {
    "task:挂周一的号-北京妇产医院": true,
    "task:买山药粉": true,
    "task:做鸡肉干": true,
    "task:确认一下 AI 资讯数据来源和已发布笔记数据是否正确": true,
    "task:和杜爽爽视频": true,
    "task:调研一下爆款笔记，关键词：生育、成为妈妈、怀孕": true
  }
};
